Add treat404AsError property to region mapped CSV item
TerriaJS/terriajs pull request #3453
Opened 2019-06-05 04:47 UTC by rowanwins

Currently when a `RegionMapping` provider crosses the anti-meridian (for example countries in the south pacific) the bounding box property the regionMapped provided means that tiles are requested outside the real area of interest, this results in many 404 errors, which in turn [triggers an error on the ImageryLayerCatalogItem](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/ImageryLayerCatalogItem.js#L1078-L1113) because the associated catalogItem (a `CsvCatalogItem`) does not have a `treat404AsError=false`.

2019-06-07 01:47 UTC, kring requested changes
The code change looks good, but this PR also adds the SPC regions. We don't want to do that, do we?

2019-06-07 03:09 UTC, rowanwins commented
Yeah I did wonder about that, the reason I added them in was that so someone might be able to see a troublesome tileset.

2019-06-07 03:42 UTC, kring commented
I'm ok with adding the new region types to our common regionMapping.json, but they can't use generic aliases like "COUNTRY". That alias is already assigned to a different region type, for one things.

2019-06-07 03:43 UTC, kring commented
I saw the 404 problem this morning with the SED_2018 region type, so finding a troublesome tileset isn't a problem. :)

2019-06-11 04:39 UTC, kring approved these changes

2019-06-11 04:39 UTC, merged