Make help panel contents customisable
TerriaJS/terriajs pull request #4187
Opened 2020-04-01 03:05 UTC by reginapramesti

### What this PR does

Fixes https://github.com/TerriaJS/terriajs/issues/4161 and https://github.com/TerriaJS/terriajs/issues/4182

Made some changes to the way the help panel is implemented. This is so that the help panel contents are more modular, and could be individually customised in every map

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

2020-04-29 05:19 UTC, reginapramesti commented
Things to unit test:
- [ ] The number of help items equals the number of items listed on config
- [ ] Providing no content will not add any text
- [ ] Some markdown text content will produce x number of items on the video panel
- [ ] Providing no icon will not break, instead use default icon
- [ ] Providing x icon will use that icon if exists in terria
- [ ] Providing no video and/or placeholder images will not break, just don't show video
- [ ] Providing video and placeholder images -> expect a video component

2020-05-07 12:15 UTC, soyarsauce requested changes
Hi Regina - this looks really really awesome!
Could you please open a PR for TerriaMap to include the intended default panels and content that we would ship by default?
Really good work with some basic check-if-it-renders tests, too!

2020-05-07 12:15 UTC, soyarsauce commented on test/ReactViews/Map/Panels/HelpPanel/HelpPanelSpec.tsx
> +      // Not sure how to compare icons so I just used the gylph.id
this is fine

2020-05-07 12:15 UTC, soyarsauce commented
Once you add the terriamap PR, merge this + the terriamap-to-mobx together and :shipit:

2020-05-08 08:41 UTC, reginapramesti commented on lib/ReactViews/Map/Panels/HelpPanel/StyledHtml.jsx
> +  ${props => props.darkBg && `background-color: ${props.theme.textDarker};`}
Yup that's true, will do that then

2020-05-11 02:55 UTC, reginapramesti commented
TerriaMap PR created! https://github.com/TerriaJS/TerriaMap/pull/445

2020-05-11 07:08 UTC, reginapramesti commented on lib/ReactViews/Map/Panels/HelpPanel/HelpPanelItem.jsx
> +      : "start"; // TODO: check what default icon should be
Oops I completely forgot to do this, but now it's replaced with the video icon (which I believe is more appropriate?)

2020-05-11 11:25 UTC, merged