Mobx WebCoverageService "Clip and ship" for WMS
TerriaJS/terriajs pull request #4461
Opened 2020-06-22 09:29 UTC by nf-s

### WCS support for WMS + basic data export UI

Includes:

- Basic `ExportableData` interface 
  - Return URL to download
  - Return file blob and filename to download
`ExportData` react component with simple button
- CSV download
- WebCoverageService call function
- Extend `UserDrawing` to have rectangle drawing
- Add `onMouseMove` option to `MapInteractionMode`

Fixes https://github.com/TerriaJS/terriajs/issues/4340

Test catalog JSON:

```json
{
  "homeCamera": {
    "north": -8,
    "east": 158,
    "south": -45,
    "west": 109
  },
  "catalog": [
    {
      "name": "Water Observations from Space Daily (WOfS Daily Observations)",
      "type": "wms",
      "layers": "wofs_albers",
      "url": "https://ows.dea.ga.gov.au/",
      "linkedWcsUrl": "https://ows.dea.ga.gov.au/",
      "linkedWcsCoverage": "wofs_albers",
      "opacity": 1
    }
  ]
}
```

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

2020-06-22 09:29 UTC, nf-s commented
How to handle errors? I have been throwing strings around.

2020-06-25 06:34 UTC, tephenavies requested changes
This is pretty good. It works from the data catalogue (except it requires someone to close the data catalogue before continuing. Maybe starting a user drawing could close the explorer panel? Or there might be a better place to put that).

Could you fix it not working from the workbench? Currently it does the whole process of exporting except calling `FileSaver` since that logic is only in ExportData.tsx

2020-06-25 13:14 UTC, nf-s commented on lib/Models/MapInteractionMode.ts
> +  // drawRectangle?: boolean;
I have commented out `drawRectangle` as it refers to unimplemented (in mobx) drawing rectangle with SHIFT + drag

2020-06-25 13:14 UTC, nf-s commented on lib/Models/UserDrawing.ts
> +        }
I removed my old mouse move event stuff because I found `viewState.mouseCoords`

2020-06-25 13:14 UTC, nf-s commented on lib/ReactViews/Analytics/ParameterEditor.jsx
> +// import RectangleParameterEditor from "./RectangleParameterEditor";
I have removed `RectangleParameterEditor` as it isn't implemented in mobx

2020-06-25 13:14 UTC, nf-s commented on lib/ReactViews/Notification/MapInteractionWindow.tsx
> +
I don't know react well, do you need `propTypes` and React.Component generic props definition?

2020-06-25 13:14 UTC, nf-s commented on lib/ReactViews/Notification/MapInteractionWindow.tsx
> +  // }
`contextItem` doesn't exist in mobX.

2020-06-25 13:19 UTC, nf-s reviewed
> This is pretty good. It works from the data catalogue (except it requires someone to close the data catalogue before continuing. Maybe starting a user drawing could close the explorer panel? Or there might be a better place to put that).

I added an `onEnable?: (viewState: ViewState) => void;` option for `MapInteractionMode`. This also ties into using `viewState.mouseCoords` for the rectangle drawing. 

> Could you fix it not working from the workbench? Currently it does the whole process of exporting except calling FileSaver since that logic is only in ExportData.tsx

Fixed it! I didn't even realise there was an Export button.

2020-06-25 13:21 UTC, nf-s commented on lib/Models/MapInteractionMode.ts
>    uiMode?: UIMode; // diff tool hack for now
classic Wing

2020-06-25 13:27 UTC, nf-s commented
@steve9164 please let me know which of the checklist items you think are worth looking into.

2020-06-26 01:43 UTC, steve9164 commented
You're failing a couple of UserDrawing tests across all browsers:

```
1) function clickedExistingPoint detects and handles if existing point is clicked

     UserDrawing

     Expected false to be truthy.

@build/TerriaJS-specs.js:385:180408

     Expected 2 to equal 3.

@build/TerriaJS-specs.js:385:180441

2) polygon is only drawn once

     UserDrawing

     Expected false to be truthy.

@build/TerriaJS-specs.js:385:182794

     Expected 1 to equal 2.

@build/TerriaJS-specs.js:385:182827

     Expected false to be truthy.

@build/TerriaJS-specs.js:385:183127

     Expected 1 to equal 2.

@build/TerriaJS-specs.js:385:183160
```

2020-06-26 02:11 UTC, steve9164 commented
I cannot use either the export feature or measure tool with these latest changes

2020-06-26 04:11 UTC, nf-s reviewed
working!

2020-06-26 05:41 UTC, nf-s commented on CHANGES.md
>  * (💫The next rad feature💫 but please be mostly bug fixes from now until June!)
Lol

2020-06-29 03:48 UTC, nf-s commented on lib/Models/UserDrawing.ts
> +          this.mouseMoveObserveDispose = observe(viewState.mouseCoords, () => {
done

2020-06-29 05:22 UTC, tephenavies approved these changes

2020-06-29 05:23 UTC, merged