Port GeoRSS to mobx
TerriaJS/terriajs pull request #4493
Opened 2020-06-30 21:56 UTC by zoran995

### What this PR does

Port GeoRSS from master to mobx, also added support to skip items without geometry (not sure if that is considered to be valid GeoRSS file but it happens with FAO geonetwork GeoRSS response).

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

2020-07-01 07:43 UTC, steve9164 commented
I'm going to review and merge this after we get #4466 merged (which should be before the end of the week).

2020-07-05 23:54 UTC, tephenavies requested changes

2020-07-06 11:06 UTC, zoran995 commented on lib/Models/GeoRssCatalogItem.ts
> +      if (author.length === 0) {
Should be fixed now. Conflicts with mobx branch are resolved

2020-07-09 09:41 UTC, steve9164 commented
Tests passing here: https://travis-ci.org/github/TerriaJS/terriajs/builds/706445766

Thanks for the PR!

2020-07-09 09:42 UTC, tephenavies approved these changes

2020-07-09 09:42 UTC, merged