Mobx: ArcGisPortal models
TerriaJS/terriajs pull request #4496
Opened 2020-07-02 00:27 UTC by rowanwins

### What this PR does

This PR adds a new `ArcGisPortalGroup` model for harvesting for ArcGIS portals. It also includes an `ArcGisPortalItemReference` which converts things into other Terria models.

I'm currently experiencing some issues in the jasmine tests with the `ArcGisPortalItemReference` not properly creating the `previousTarget` but it seems to work ok in the browser.

Here's some sample configurations. Note that a couple of them require use within something like NSW Digital Twin where we can get a users token.
````
{
 "catalog": [
    {
      "type": "arcgis-portal-item",
      "url": "https://portal.spatial.nsw.gov.au/portal",
      "itemId": "66fabd8c23074ecc85883e0086419adc",
      "name": "Road Segments"
    },
    {
      "type": "arcgis-portal-group",
      "name": "All open Content",
      "url": "https://portal.spatial.nsw.gov.au/portal"
    },
    {
      "type": "arcgis-portal-group",
      "name": "Users Private Content",
      "url": "https://portal.spatial.nsw.gov.au/portal",
      "searchParams": {
        "q": "access:private and type:'Feature Service"
      }
    },
    {
      "type": "arcgis-portal-group",
      "name": "Users Groups",
      "url": "https://portal.spatial.nsw.gov.au/portal",
      "groupBy": "usersGroups"
    },
    {
      "type": "arcgis-portal-group",
      "name": "Organisations Groups",
      "url": "https://portal.spatial.nsw.gov.au/portal",
      "groupBy": "organisationsGroups",
      "groupSearchParams": {
        "q": "orgid:0123456789ABCDEF"
      }
    }
  ]
}
````

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

2020-07-29 08:34 UTC, tephenavies requested changes

2020-07-29 22:26 UTC, rowanwins commented on lib/Traits/ArcGisPortalItemFormatTraits.ts
> +  urlRegex?: string | RegExp;
For some reason these lines ([here](https://github.com/TerriaJS/terriajs/pull/4496/files#diff-ba7e5f5f11487cf6fd0b2e018c843db4R219) and [here](https://github.com/TerriaJS/terriajs/pull/4496/files#diff-ba7e5f5f11487cf6fd0b2e018c843db4R235)) were giving me massive grief, every string variant I tried of them wouldn't work properly, so I gave up

2020-07-29 23:09 UTC, rowanwins commented on lib/Models/ArcGisPortalCatalogGroup.ts
> +      if (a.name === undefined || b.name === undefined) return 0;
addressed

2020-07-30 01:25 UTC, rowanwins commented on lib/Traits/ArcGisPortalItemFormatTraits.ts
> +  urlRegex?: string | RegExp;
Just to clarify the example further

````
const r = /MapServer\/\d/
const r2 = new RegExp(/MapServer\/\d/)
const r3 = new RegExp('/MapServer\/\d/')

const url = 'https://portal.spatial.nsw.gov.au/server/rest/services/NSW_Features_of_Interest_Category/MapServer/0'

r.test(url)=> true
r2.test(url)=> true
r3.test(url)=> false
````

2020-07-30 01:44 UTC, soyarsauce commented on lib/Traits/ArcGisPortalItemFormatTraits.ts
> +  urlRegex?: string | RegExp;
Give this a whirl:
`const r4 = new RegExp('MapServer\/\\d')`

```
r4.test(url);
// true
```

2020-07-30 02:11 UTC, soyarsauce approved these changes
Let's merge this & address https://github.com/TerriaJS/terriajs/pull/4496#pullrequestreview-457147754 as part of another ticket

2020-07-30 02:13 UTC, soyarsauce commented on lib/Traits/ArcGisPortalItemFormatTraits.ts
> +  urlRegex?: string | RegExp;
https://github.com/TerriaJS/terriajs/issues/4593

2020-07-30 02:44 UTC, tephenavies approved these changes

2020-07-30 02:47 UTC, merged