Delta3 ui bottom rebased
TerriaJS/terriajs pull request #4533
Opened 2020-07-10 06:05 UTC by soyarsauce

### What this PR does

Addresses https://github.com/TerriaJS/terriajs/issues/4371 https://github.com/TerriaJS/terriajs/issues/4372 & https://github.com/TerriaJS/terriajs/issues/4375

### Checklist

-   [x] unit tests n/a
-   [x] I've updated CHANGES.md with what I changed.

2020-07-13 03:49 UTC, reginapramesti commented
![image](https://user-images.githubusercontent.com/16102484/87268993-50dc0800-c50f-11ea-9266-65330b0ebce9.png)
Viewing the map on my laptop screen cuts off parts of the delta panel, so maybe we need to add a scrollbar as a temporary quick fix? And also the "No map data enabled" part covers the delta panel too in smaller screens 😬

2020-07-13 04:09 UTC, reginapramesti requested changes
Looks really good 👏  I think we just need to make the delta panel more visible on slightly smaller screens (since it doesn't take too small a screen to make it difficult to read/use). Should be good to go once we give that a quick fix! @soyarsauce

2020-07-13 08:25 UTC, soyarsauce commented on lib/ReactViews/Workbench/Controls/ViewingControls.jsx
> +      this.props.item.terria.timelineStack.removeAll();
Yeah if they explicitly always want timeline, then we leave it so

2020-07-13 09:27 UTC, soyarsauce commented
> Looks really good 👏 I think we just need to make the delta panel more visible on slightly smaller screens (since it doesn't take too small a screen to make it difficult to read/use). Should be good to go once we give that a quick fix! @soyarsauce

Delta panel now resizes against viewport + some buffer, it will have to do for now.

2020-07-14 01:02 UTC, soyarsauce commented
https://github.com/TerriaJS/terriajs/pull/4533/commits/d3e9c0b61915ee6327c5d4bb08ffb3a3f21ce393 also fixes https://github.com/TerriaJS/terriajs/issues/4537

2020-07-14 02:15 UTC, reginapramesti approved these changes
Thanks heaps for making it work on smaller screen 👏 really appreciate it! Looks good to me now

2020-07-14 02:22 UTC, merged