tsxified DateTimePicker + moved objectifyDates to DiscretelyTimeVaryingMixin
TerriaJS/terriajs pull request #4576
Opened 2020-07-28 07:18 UTC by nf-s

### tsxified DateTimePicker + moved objectifyDates to DiscretelyTimeVaryingMixin

This is an attempt to fix performance issues related to `objectifyDates` in `DiscretelyTimeVaryingMixin`, which creates a huge object of this structure:

```ts
type DatesObject<T> = {
  [key: number]: T;
  dates: Date[];
  indice: number[];
};
type ObjectifiedDates = DatesObject<ObjectifiedYears>;
type ObjectifiedYears = DatesObject<ObjectifiedMonths>;
type ObjectifiedMonths = DatesObject<ObjectifiedDays>;
type ObjectifiedDays = DatesObject<ObjectifiedHours>;
type ObjectifiedHours = DatesObject<Date[]>;
```

**So far I have**

- Tsxified `DateTimePicker`
- Moved `objectifyDates` to `DiscretelyTimeVaryingMixin` as a `@computed` property.

This has solved most of the performance issues, so now `objectifyDates` isn't computed ~8 times when a WMS item is added to the workbench, and recomputed every time the `currentDate` is changed

**Problems**

- If the Time Filter is enabled, picking a new `currentDate` re-computes  `objectifyDates`
  - This has something to do with `TimeFilterMixin.timeFilterPropertyName` and `DiscretelyTimeVarying.currentTime`
-  `objectifyDates` isn't efficient, will try to refactor to reduce complexity

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

2020-08-03 06:26 UTC, soyarsauce commented
Double check if this addresses https://github.com/TerriaJS/terriajs/issues/4518

2020-08-13 08:58 UTC, nf-s commented
> Double check if this addresses #4518

This is fixed now.

2020-08-14 05:31 UTC, rowanwins approved these changes
Looks good to me from the refactored objectifyDates perspective. Can't comment much on the tsx or style components but it works :)

2020-08-14 06:08 UTC, soyarsauce requested changes
Looks good, great work - and understanding the styles are just ripped straight from the old scss ones, it's a good start. Should aim to use the new generic components wherever possible, let's just go for theme for now.

2020-08-14 06:08 UTC, soyarsauce commented on lib/ReactViews/BottomDock/Timeline/DateTimePicker.tsx
> +              css={`
Add some sort of title - only especially important as the button doesn't have any text in it (it's just an icon as sole child)

```suggestion
            <button
              title={t("diffTool.datePicker.dateButtonTitle")}
              css={`
```

2020-08-14 06:08 UTC, soyarsauce commented on lib/ReactViews/BottomDock/Timeline/DateTimePicker.tsx
> +                css={`
Add an appropriate title here too

2020-08-17 01:27 UTC, nf-s commented on lib/ReactViews/BottomDock/Timeline/DateTimePicker.tsx
> +const Grid = styled.div`
alright i'll leave this for now

2020-08-19 06:28 UTC, soyarsauce approved these changes

2020-08-19 06:28 UTC, merged