All info content to support json
TerriaJS/terriajs pull request #4681
Opened 2020-08-28 04:02 UTC by rowanwins

### What this PR does

Related to #4612 

So in `master` we had a `Metadata` class which could contain all weird and wonderful things. In `next` we haven't ported that and are largely reliant on `InfoSection`'s which just have a content field which only accepts a `string`.

In master with Metadata we could have JSON objects which allowed us to support more complex objects such as data source stuff from a WMS
![Screen_2020_08_28](https://user-images.githubusercontent.com/6735870/91519745-ce7c9b80-e936-11ea-84cf-52e48dbdabbd.jpg)

So there are few options
1. Re-implement the `Metadata` class from `master` in `next`
2. Extend the `InfoSection` to support JSON objects
  - The second approach feels like it could potentially simplify things by consolidating places where info and metadata is stored. 

This PR is a basic start on that second approach. If we agreed that this was a helpful way forward we could finish tidying it up.

Being able to reference JSON metadata is a requirement for Kaleidoscope as they want to have a button in the preview section related to the layer metadata from a WMS. So this PR also includes a exposing the info array as an object, which perhaps isn't ideal, but it works.

````
       "info": [
         {
           "name": "",
           "content": "{{#infoAsObject.DataDescription}}<a href='{{infoAsObject.DataDescription.MetadataURL.OnlineResource.xlink:href}}'><button class='tjs-_buttons__btn tjs-_buttons__btn-primary'>Find metadata in Marlin</button></a>{{/infoAsObject.DataDescription}}{{^infoAsObject.DataDescription}}<p>No Marlin Metadata recorded</p>{{/infoAsObject.DataDescription}}"
          }
       ]
````

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

2020-08-28 04:10 UTC, rowanwins commented
Here is what the result looks like from the deployment
![InNext](https://user-images.githubusercontent.com/6735870/91520256-31bafd80-e938-11ea-905d-d10ab18e9843.jpg)

2020-08-28 04:12 UTC, rowanwins commented on lib/Traits/CatalogMemberTraits.ts
> +  content?: string | JsonObject | null;
This is the key change

2020-08-28 04:12 UTC, rowanwins commented on lib/ModelMixins/CatalogMemberMixin.ts
> +    get infoAsObject() {
This supports accessing infoSections within the mustache templates for feature info

2020-08-28 04:22 UTC, soyarsauce commented
It seems better if this is another trait, rather than clobbering the `InfoSectionTraits`'s content trait - that way we could render both the json editor as well as a markdown editor (ignoring the fact we have no way to signal markdown-parsability of a trait in code yet)

![image](https://user-images.githubusercontent.com/9134432/91520890-ceca6600-e939-11ea-8050-5b4bbc19e1b5.png)

2020-09-02 02:16 UTC, rowanwins commented
Just dropping a note that I've started refactoring so that there is a new trait called `contentAsObject` rather than mixing types.

2020-09-18 01:44 UTC, steve9164 requested changes

2020-09-21 03:05 UTC, rowanwins commented on lib/ModelMixins/CatalogMemberMixin.ts
> +          } else if (infoItem.contentAsObject !== undefined) {
Not sure I follow here @steve9164... are you suggesting that where we have 2 info items that have the same `name` the one that has `contentAsObject` ought to be what is returned?

2020-09-21 03:09 UTC, steve9164 commented on lib/ModelMixins/CatalogMemberMixin.ts
> +          } else if (infoItem.contentAsObject !== undefined) {
That is what I'm suggesting. Is that something we can/should do here?

2020-09-24 03:44 UTC, rowanwins commented on lib/ModelMixins/CatalogMemberMixin.ts
> +          } else if (infoItem.contentAsObject !== undefined) {
Have now amended, I think that makes sense

2020-09-29 03:43 UTC, steve9164 submitted a review, later dismissed

2020-09-29 05:29 UTC, steve9164 commented
Missing a CHANGES.md entry

2020-09-29 05:39 UTC, steve9164 requested changes
@rowanwins Please add a few lines to CHANGES.md about the various new features and add a test where the service description comes through as an info item with `contentAsObject`. Any additional tests you can think of would also be great.

2020-09-30 03:56 UTC, steve9164 approved these changes

2020-09-30 03:56 UTC, merged