Create merge TraitsOption for objectArrayTrait
TerriaJS/terriajs pull request #5144
Opened 2021-01-19 10:50 UTC by nf-s

### Create `merge` `TraitsOption` for `objectArrayTrait`

Fixes https://github.com/TerriaJS/terriajs/issues/5048

Alternatively, this could be implemented somewhere in `lib\Models\createCombinedModel.ts`

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

2021-02-18 06:46 UTC, nf-s commented on lib/Traits/CatalogMemberTraits.ts
> +    merge: false
`LegendTraits` is the only `ObjectArrayTrait` where I have set `merge: false` - I'm sure there will be others

2021-02-25 00:49 UTC, steve9164 requested changes
Please add a note a the top of alpha.66 in CHANGES.md that there is a breaking change to `legends` in `CatalogMemberTraits`. Something like:

Potentially breaking changes:
* Changed merging behaviour of Trait `legends` (of type `LegendTraits`) in `CatalogMemberTraits`. This affects legends on all CatalogMember models. Legend objects in higher strata now replace values in lower strata that match by index, rather than merging properties with them.

2021-02-25 01:43 UTC, nf-s commented
> 
> 
> Please add a note a the top of alpha.66 in CHANGES.md that there is a breaking change to `legends` in `CatalogMemberTraits`. Something like:
> 
> Potentially breaking changes:
> 
>     * Changed merging behaviour of Trait `legends` (of type `LegendTraits`) in `CatalogMemberTraits`. This affects legends on all CatalogMember models. Legend objects in higher strata now replace values in lower strata that match by index, rather than merging properties with them.

@steve9164 done!

2021-02-25 03:51 UTC, steve9164 approved these changes

2021-02-25 03:52 UTC, merged