Implement highlight/hide all for item search results.
TerriaJS/terriajs pull request #5232
Opened 2021-02-11 06:08 UTC by na9da

### What this PR does

Fixes #5148 

Implements highlight/hide all search results for 3d-tiles. The way it works is by listening for `tileVisible` events for the tileset and tagging each feature with a matching ID and then applying a cesium `color` or `show` expression for all features with that tag.

The alternate solution was to convert a search query to cesium style expression, however this wont work for complex queries involving full text search.

I have checked the performance of the current implementation and it didn't seem too bad.

### Testing

Using the same dataset from https://github.com/TerriaJS/terriajs/pull/5112#issue-545071441

### Checklist

-   ~[ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)~
-   [x] I've updated CHANGES.md with what I changed.

2021-02-12 08:52 UTC, KeyboardSounds requested changes
Watching the search feature get better and better is so exciting! "highlight all" in particular adds a lot to how useful it is, making it easier for users to see patterns in their data. Nice work on those one ⭐

IMO, when you hit the search button, by default all of the buildings that match the search criteria should be highlighted, rather than the user having to click "highlight all".

Some issues I spotted when I was testing:
- The size of the text on the HighlightAll buttons seems to change when you click the button. Also, since it's a toggle, it should probably be a checkbox or something rather than a button to make the current state clearer.
- If you click through enough (10+) search results, all of the buildings disappear. This could be a Cesium problem struggling with loading and unloading all the tiles, but it's worth investigating.
- If I select a small (~< 5M) tall building in the search results, it doesn't get highlighted and the feature info panel for it is stuck on loading. Possibly because the tile that contains it never loads?
- If I bring up the search tool and then remove the dataset from the workbench, the search tool stays on screen.

2021-02-16 02:27 UTC, na9da commented on lib/Models/Cesium3DTilesCatalogItem.ts
> +    const watch = (tile: Cesium3DTile) => {
I have extracted it out to a method called `_watchForNewTileFeatures`.

2021-02-16 03:11 UTC, na9da commented on lib/ReactViews/Tools/ItemSearchTool/SearchResults.tsx
> +      )}
I have addressed the basic concern of improving clarity by extracting the individual components into a new component called `MapEffects` to make it clear that it is applying some effect to the map.

On the use of renderless components, I think it is a known [pattern](https://shopify-1.gitbook.io/react/4.-advanced-patterns/renderless-components) in react. In this case, like you said, we could bind these effects to the click events but then have to remember to remove the effects when the component unmounts in some other useEffect disposer function. With renderless components we can extract these two related bits of logic into a separate component that takes care of the mount/unmount behaviors. 

In general, I think, renderless components are useful when you want perform some side-effect on mount/update and then cleanly dispose the effect on unmount.

2021-02-16 03:35 UTC, na9da commented
Thanks for the awesome feedback @KeyboardSounds!

All are great points, I have addressed most of them or provided justifications where necessary.

> IMO, when you hit the search button, by default all of the buildings that match the search criteria should be highlighted, rather than the user having to click "highlight all".

That's a good idea, I have made "highlight all" the default behavior.

> The size of the text on the HighlightAll buttons seems to change when you click the button. Also, since it's a toggle, it should probably be a checkbox or something rather than a button to make the current state clearer.

I have fixed the font-size issue. the checkbox thing is a good suggestion that I'll look at when I work in some of the design changes from @philipgrimmett 's new design.

> If you click through enough (10+) search results, all of the buildings disappear. This could be a Cesium problem struggling with loading and unloading all the tiles, but it's worth investigating.

Good catch. This was happening because of a previous change I introduced for calculating modelMatrix from transformation traits.

https://github.com/TerriaJS/terriajs/blob/e0df615a65533aa26d564ba8de9955ebcb0cf8d8/lib/ModelMixins/Cesium3dTilesMixin.ts#L233-L238

It was modifying the modelMatrix and then when `mapItems` recomputes due to some change in styles, it incorrectly dereives new the modelMatrix from the previous modelMatrix and the traits. Whereas the correct behavior is to keep a copy of the original `tileset.root.transform` and re-compute every time from the original transform an the transformation traits. I have fixed the problem below also ensuring that the modelMatrix is re-computed only if the transformation traits change.

https://github.com/TerriaJS/terriajs/blob/20f9f46e52ff30ca897fada241180e488587a5f9/lib/ModelMixins/Cesium3dTilesMixin.ts#L252-L253

> If I select a small (~< 5M) tall building in the search results, it doesn't get highlighted and the feature info panel for it is stuck on loading. Possibly because the tile that contains it never loads?

Yes this is a problem. The only way to fix that would be to provide the lat/lon/height of features when indexing. This helps us zoom in closer to the building. The feature info panel will timeout after 60secs if it cannot resolve the feature.

> If I bring up the search tool and then remove the dataset from the workbench, the search tool stays on screen.

Fixed!

2021-02-16 04:05 UTC, na9da commented
Another change I made:

Previously we were listening only for `tileVisible` events to apply the highlight. This resulted in a visible flicker because the tile features would render with the original style then the new highlight is applied and there is a delay for the highlight to appear. We now listen for both `tileVisible` and `tileLoad` events, this ensures that the highlight is applied from the start for newly loaded tiles.

2021-02-18 02:39 UTC, KeyboardSounds commented on lib/ModelMixins/Cesium3dTilesMixin.ts
>      @action
@na9da?

2021-02-18 02:46 UTC, KeyboardSounds commented on lib/ReactViews/Tools/ItemSearchTool/SearchResults.tsx
> +      )}
Consider me convinced! I like the new way you've done it with more of a separation between view and render logic a lot better.

2021-02-18 08:33 UTC, na9da commented on lib/ModelMixins/Cesium3dTilesMixin.ts
>      @action
Done!

2021-02-18 08:33 UTC, KeyboardSounds approved these changes

2021-02-21 23:07 UTC, merged