Initial message
TerriaJS/terriajs pull request #5322
Opened 2021-03-12 04:38 UTC by KeyboardSounds

### What this PR does

Fixes #5160

Plus, the Notification refactor that nobody asked for!

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

2021-03-12 06:59 UTC, nf-s requested changes
When I click on an item in the Data Catalog (using the default `simple` catalog)  - I get this

![image](https://user-images.githubusercontent.com/6187649/110903833-296a6300-835c-11eb-9ce2-e5522dc74af7.png)

I also get this, when I click on `Marine water quality grids for the Great Barrier Reef region - monthly data` and then `number_of_valid_observations`

![image](https://user-images.githubusercontent.com/6187649/110904120-93830800-835c-11eb-8c2b-00bbb9ad4fb2.png)

2021-03-12 06:59 UTC, nf-s commented on lib/ModelMixins/AsyncMappableMixin.ts
> +      await this.showInitialMessageIfRequired();
I'm not sure this is the best place for this. What about putting something like:
```ts
if (ShowableMixin.isMixedInto(item) {
   await item.showInitialMessageIfRequired();
}
```
in https://github.com/TerriaJS/terriajs/blob/6c205d9fcb48857b098993e5723dedd5a5e24683/lib/Models/Workbench.ts#L195-L201

2021-03-12 06:59 UTC, nf-s commented on CHANGES.md
>  * [The next improvement]
Can you please add an entry about `ShowableMixin`

2021-03-12 06:59 UTC, nf-s commented on lib/ReactViewModels/ViewState.ts
> +import NotificationState from "./NotificationState";
There is still a `Notification` interface in this file

2021-03-12 06:59 UTC, nf-s commented on lib/ReactViewModels/ViewState.ts
> +import NotificationState from "./NotificationState";
(at line 43 - it won't let me comment on it)

2021-03-12 06:59 UTC, nf-s commented on lib/ReactViewModels/ViewState.ts
>      this._unsubscribeNotificationListener = terria.notification.addEventListener(
I think that if we're refactoring `Notification` stuff, we should probably get rid of the un-typed Cesium event handler in 

https://github.com/TerriaJS/terriajs/blob/20304b657d5e96766009f770a0c985f2345f8264/lib/Models/Terria.ts#L258

I know that `notificationState` should probably be in `ViewState`, but it needs to be visible to the entire codebase (especially the model layer). Could we maybe move it into `Terria.ts` and remove it from `ViewState`? As everywhere has access to the `terria` object, and then we can get rid of the `CesiumEvent` passing `Notifications` between `Terria` and `ViewState`.

2021-03-12 06:59 UTC, nf-s commented on lib/ReactViewModels/ViewState.ts
> +import NotificationState from "./NotificationState";
https://github.com/TerriaJS/terriajs/blob/5b7d0155473d3537b7a2402a6fe40566080113cc/lib/ReactViewModels/ViewState.ts#L42-L53

2021-03-12 06:59 UTC, nf-s commented on lib/ReactViewModels/ViewState.ts
>    }
Can we make this a `@computed` property?

2021-03-12 06:59 UTC, nf-s commented on lib/ReactViews/Notification/Notification.tsx
> +    return <></>;
I like returning `null` in these situations

2021-03-12 06:59 UTC, nf-s commented on lib/ReactViews/Notification/Notification.tsx
> +    return <></>;
probs doesn't matter though

2021-03-12 06:59 UTC, nf-s commented on lib/Traits/CatalogMemberTraits.ts
> +import objectTrait from "./objectTrait";
```suggestion
```

2021-03-12 07:02 UTC, nf-s commented on lib/ReactViewModels/ViewState.ts
>      this._unsubscribeNotificationListener = terria.notification.addEventListener(
This approach could also be used for the `terria.error` Cesium event handler

2021-03-15 07:14 UTC, KeyboardSounds commented
TODO: Rewrite to observe changes to viewstate in an autorun, and run then, rather than in load

2021-04-14 01:39 UTC, nf-s commented
Also, when you merge in `next` please take into account changes made to `Notification.jsx` here - https://github.com/TerriaJS/terriajs/pull/5413 

https://github.com/TerriaJS/terriajs/commit/08ea7a227a36902a00357710306225aa6f40e6cb#diff-a07b9cfd11367978cf4ae8e66b86910d059019e214c2a9bb5bf7403b2f95c617

2021-04-28 05:02 UTC, nf-s requested changes

2021-04-28 05:10 UTC, nf-s commented on lib/ModelMixins/AsyncMappableMixin.ts
> +      await this.showInitialMessageIfRequired();
We discussed this, you were right

2021-04-28 05:10 UTC, nf-s commented on lib/ReactViewModels/ViewState.ts
>      this._unsubscribeNotificationListener = terria.notification.addEventListener(
Never mind, not needed right now

2021-05-03 06:09 UTC, nf-s requested changes

2021-05-03 06:09 UTC, nf-s commented on lib/Models/Terria.ts
> +          // } as Notification);
stray comments

2021-05-03 06:09 UTC, nf-s commented on lib/ModelMixins/MappableMixin.ts
> +import saveModelToJson from "../Models/saveModelToJson";
this is unused

2021-05-03 06:09 UTC, nf-s commented on lib/ModelMixins/ShowableMixin.ts
> +};
This isn't used

2021-05-03 06:09 UTC, nf-s commented on lib/ModelMixins/ShowableMixin.ts
> +import Property from "terriajs-cesium/Source/DataSources/Property";
This isn't used

2021-05-04 05:08 UTC, nf-s requested changes
Did we decide to get rid of `ShowableTraits`? I can't remember

2021-05-20 06:50 UTC, nf-s approved these changes

2021-05-20 07:01 UTC, merged