Don't render help panel on init
TerriaJS/terriajs pull request #5431
Opened 2021-04-18 17:33 UTC by zoran995

### What this PR does

Fixes #<insert issue number here if relevant>

Currently we are rendering entire help panel at the start although it is not visible, and it might also resolve #4670. Profiler is reporting significant increase of the initial rendering time. 
before this change
![image](https://user-images.githubusercontent.com/19208948/115154709-8dc7c300-a07c-11eb-8e86-9896abd11d54.png)

after this change
![image](https://user-images.githubusercontent.com/19208948/115154729-a46e1a00-a07c-11eb-8ce7-c3cf53864112.png)

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated CHANGES.md with what I changed.

2021-04-26 01:57 UTC, steve9164 submitted a review, later dismissed

2021-04-26 02:49 UTC, steve9164 requested changes
I like the idea but this disables slide-in, slide-out animations. We should improve this component, but I'm not sure this is the way to do that.

Another idea would be to render only a white box while animating (that should be much cheaper than rendering the whole help panel) or maybe only render the first 320px column, not the HelpVideoPanel too while animating. What do you think @philipgrimmett @wibily ?

2021-04-26 02:50 UTC, steve9164 commented
BTW you can test this PR as-is at http://ci.terria.io/zoran-help-panel/

2021-04-27 00:24 UTC, wibily commented
I don't think its that big of an issue that we break animations to save on initial rendering times as we don't have a consistent animation pattern within the app. For example, the story panel isn't animated either and the workbench sliding animation could also do with some work. My opinion is that we conditionally render the HelpPanel and remove the css transition properly so that we can deal with sliding panels holistically at a later date

2021-09-30 02:40 UTC, na9da commented
Sorry I didn't see this PR when I made a fix for the problem here #5807. It should be fixed while retaining the animation.

2021-09-30 14:45 UTC, zoran995 commented
Closing this as it is resolved in #5807

2021-09-30 14:45 UTC, closed without merging