Upgrade html-to-react dependency and fix type errors.
TerriaJS/terriajs pull request #5532
Opened 2021-06-09 08:02 UTC by na9da

### What this PR does

Upgrades `html-to-react` to latest version and fix the type errors. This is to fix the CI build errors.

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated CHANGES.md with what I changed.

2021-06-09 08:05 UTC, na9da commented on lib/ReactViews/Custom/ChartCustomComponent.ts
> +    const node = _node as any;
Casting to `any` as I think it is not worth the effort typing this properly. The nested typings is gnarly!

2021-06-09 09:26 UTC, steve9164 requested changes

2021-06-09 09:26 UTC, steve9164 commented on package.json
> -    "domhandler": "^2.4.2",
I think we shouldn't import "domhandler" without having a direct dependency on "domhandler".

2021-06-09 09:34 UTC, zoran995 commented
@na9da I am afraid that this could cause the same issue as #5468 although I might be missing something, check the https://github.com/TerriaJS/terriajs/pull/5468#issuecomment-832607495

2021-06-10 00:15 UTC, na9da commented
Thanks @zoran995 for pointing that out. Considering this and also @steve9164's comment, I think we should define the type locally and use that instead of depending on domhandler. We are currently importing it only for the type definition. Upgrading `html-to-react` itself is not a problem though.

2021-06-10 00:38 UTC, na9da commented
Sorry that, I overwrote the previous changes.

2021-06-10 01:50 UTC, steve9164 approved these changes

2021-06-10 03:21 UTC, merged