Terria error importance
TerriaJS/terriajs pull request #5821
Opened 2021-09-16 13:12 UTC by nf-s

### What this PR does

Fixes #<insert issue number here if relevant>

This is a description of what I've done in this PR, especially explaining choices made to make the reviewer's job easier. If I don't replace this paragraph with an actual description, my PR will probably be ignored.

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [ ] I've updated CHANGES.md with what I changed.

2021-10-12 12:24 UTC, nf-s commented on lib/Core/TerriaError.ts
>      // Find highest severity across errors (eg if one if `Error`, then the new TerriaError will also be `Error`)
This is so we don't get unnecessary levels of `TerriaError` created

2021-10-12 12:29 UTC, nf-s commented on lib/Models/Catalog/Ows/callWebCoverageService.ts
> +
doesn't need to be in `runInAction`

2021-10-12 12:31 UTC, nf-s commented on lib/Models/Catalog/SdmxJson/SdmxJsonCatalogItem.ts
> +        });
Example message 
![image](https://user-images.githubusercontent.com/6187649/136956372-bbd6fab2-d860-4aed-bcdd-dee7da3a4095.png)
http://ci.terria.io/terria-error-importance/#configUrl=https://raw.githubusercontent.com/TerriaJS/saas-catalogs-public/main/pacificmap/map-config/test.json&share=s-uHxcM1TJCeyjwWybDQo1oEMfWrT

2021-10-12 12:32 UTC, nf-s commented on lib/Models/Catalog/SdmxJson/SdmxJsonDataflowStratum.ts
> +      template += `</table>{{#terria.timeSeries.data}}<chart title="${chartName}" x-column="{{terria.timeSeries.xName}}" y-column="${this.unitMeasure}" >{{terria.timeSeries.data}}</chart>{{/terria.ti
This fixes charts being displayed even if there is no `terria.timeSeries.data` to show

2021-10-12 12:34 UTC, nf-s commented on lib/ReactViews/Custom/CustomComponent.ts
> +  readonly feature?: Feature;
these need to be optional - as they are not always passed in (and are usually passed in JS not TS)

2021-10-12 12:38 UTC, nf-s commented on lib/ReactViews/SidePanel/Branding.tsx
> +export default observer(
All I have done here is wrap in `observer`

2021-10-12 12:39 UTC, nf-s commented on lib/Core/TerriaError.ts
>      // Find highest severity across errors (eg if one if `Error`, then the new TerriaError will also be `Error`)
added as comment

2021-10-12 13:02 UTC, nf-s commented on lib/Models/Catalog/SdmxJson/SdmxJsonCatalogItem.ts
> +        });
not perfect, but a good start

2021-10-13 05:30 UTC, KeyboardSounds requested changes

2021-10-13 05:30 UTC, KeyboardSounds commented on lib/Core/Result.ts
> +  static combineEmpty(
Why not add logic to `combine` to handle the empty case, where every result is undefined? Then you don't have to call the specific function for the specific case

2021-10-13 05:30 UTC, KeyboardSounds commented on lib/Core/TerriaError.ts
>        ...parseOverrides(overrides)
Are you missing `importance` here?

2021-10-13 05:30 UTC, KeyboardSounds commented on lib/Language/en/translation.json
> +      "errorRenderingMessage": "<p>An error occurred while rendering in 3D.  This probably indicates a bug in {{appName}} or an incompatibility with your system or web browser.  We'll now switch you
Remove the `<p>` tags

2021-10-13 05:30 UTC, KeyboardSounds commented on lib/Models/Terria.ts
> +    const raiseToUser = forceRaiseToUser
This hurts my feeble brain. Use an if statement for us mere mortals?

2021-10-13 05:32 UTC, KeyboardSounds commented on lib/Core/TerriaError.ts
> +  importance?: number;
Specify how ties are broken. The JS sort function is stable, so it will be in order of appearance, but I would probably just say that the order is undefined.

2021-10-13 06:43 UTC, nf-s commented on lib/Core/Result.ts
> +  static combineEmpty(
I was having issues with types, but you're right - I ~have~ hath removed it

2021-10-13 06:47 UTC, nf-s commented on lib/Core/TerriaError.ts
>        ...parseOverrides(overrides)
No, I have added a comment why


> We don't want `importance` copied over, as it may vary between errors in the tree - and we want to be able to find errors with highest importance when diplaying the entire error tree to the user

2021-10-13 06:51 UTC, nf-s commented on lib/Core/TerriaError.ts
> +  importance?: number;
added a comment

> If two errors of equal importance are found - the first error found through depth-first search will be shown

2021-10-13 06:56 UTC, nf-s commented on lib/Models/Terria.ts
> +    const raiseToUser = forceRaiseToUser
hehe ok

2021-10-13 06:56 UTC, nf-s commented on lib/Language/en/translation.json
> +      "errorRenderingMessage": "<p>An error occurred while rendering in 3D.  This probably indicates a bug in {{appName}} or an incompatibility with your system or web browser.  We'll now switch you
👍

2021-10-13 08:03 UTC, KeyboardSounds approved these changes

2021-10-13 10:50 UTC, merged

2021-11-29 02:25 UTC, steve9164 commented on lib/ReactViews/Preview/MappablePreview.jsx
> +      );
Lost terria.timelineStack.addToTop(this.props.previewed);

Causing https://github.com/TerriaJS/terriajs/issues/5966.