Tsify map settings panel
TerriaJS/terriajs pull request #5826
Opened 2021-09-20 01:13 UTC by zoran995

### What this PR does

Fixes #<insert issue number here if relevant>

Convert map settings panel to typescript and use styled components. 
Fixed a check for Leaflet viewer so image optimisation options don't show when the viewer is 2D

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [x] I've updated relevant documentation in `doc/`.
-   [ ] I've updated CHANGES.md with what I changed.

2021-10-14 00:39 UTC, na9da commented on lib/ReactViews/Map/Panels/SettingPanel.tsx
> +}
I think it is a good decision to extract this out but maybe we should move it to `ViewerMode.ts` and also make `Terria.ts` use this function from `Terria.setViewerMode`. Let met know what you think.

2021-10-14 00:40 UTC, na9da requested changes
Thanks @zoran995 for the PR. It looks great. I have just made a small recommendation.

2021-10-14 06:50 UTC, zoran995 commented on lib/ReactViews/Map/Panels/SettingPanel.tsx
> +}
good point
it was a plan to extract it as a separate function when `Terria.setViewerMode` get merged but completely forgot about it

2021-10-16 20:50 UTC, zoran995 commented
@na9da I have extracted `setViewerMode` as you suggested. I have also taken a new version of Checkbox from our implementation and added it here as it is more flexible to use it with child elements instead of label prop

2021-10-26 06:44 UTC, na9da approved these changes
Thanks @zoran995 !

2021-10-26 06:44 UTC, merged