Wc sourcemaps
TerriaJS/terriajs pull request #5828
Opened 2021-09-20 04:38 UTC by wibily

### What this PR does
This enables sourcemaps when devmode is true (ie yarn dev). I have also disabled istandbul coverage reporter as that was interferring with source map generation

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [ ] I've updated CHANGES.md with what I changed.

2021-09-21 11:14 UTC, mwu2018 requested changes
Setting `devtool` to `eval-cheap-module-source-map` will mess up source maps.

```
        devtool: 'source-map',
        // Use eval cheap module source map for quicker incremental tests
        // devtool: dev ? 'eval-cheap-module-source-map' : 'source-map',
```

2021-09-21 14:01 UTC, wibily commented
> Setting `devtool` to `eval-cheap-module-source-map` will mess up source maps.
> 
> ```
>         devtool: 'source-map',
>         // Use eval cheap module source map for quicker incremental tests
>         // devtool: dev ? 'eval-cheap-module-source-map' : 'source-map',
> ```

Hmm, i can't seem to reproduce that. I ran
`gulp build` followed by `yarn dev` and it seems to show the source code fine?
I'm a bit hesitant to generate the full source-maps as it will make the build for dev mode even slower

2021-09-22 01:19 UTC, mwu2018 commented
I've tried again and can confirm that `sourceMaps: !!devMode` have to be changed to `sourceMaps: true` to give correct source maps. Setting `devtool` to `eval-cheap-module-source-map` is ok.  My commands follow.
```
yarn gulp build
yarn dev
```

2021-09-22 01:24 UTC, wibily commented
@mwu2018 Okay, i've made the change to sourceMaps. Could you please re-review and approve if you are happy for this to go into main?

2021-09-22 01:38 UTC, mwu2018 approved these changes

2021-09-22 01:39 UTC, merged