Wc print
TerriaJS/terriajs pull request #5933
Opened 2021-10-25 05:45 UTC by wibily

### What this PR does

Refactor to remove the last usage of create-react-class by converting PrintView to use tsx classes. I have also changed the renderLegend function to use `currentTime` instead of `discreteTime` as I'm pretty sure that discreteTime doens't exist.

To compare, I am using the dataset: Marine water quality grids for the Great Barrier Reef region - monthly data > number of observations

Main: http://ci.terria.io/main/#share=s-pCl9Rg6AWyfP0oF3GcBRkI5jnKu
wc-print: http://ci.terria.io/wc-print/#share=s-xVrTjAV430M2Mn5dUbpx3RCoOHl

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [x] I've updated CHANGES.md with what I changed.

2021-10-25 06:37 UTC, tephenavies requested changes
At the moment print view is not working at http://ci.terria.io/wc-print/. I think the issue is the `PrintView.create` function

2021-10-25 06:37 UTC, tephenavies commented on lib/ReactViews/Map/Panels/SharePanel/PrintView.tsx
>          );
I don't think this will work because methods are not bound when deriving from React.Component. I think you need the following
```suggestion
        this.printWindowIntervalId = printWindow.setInterval(
          this.checkForImagesReady.bind(this),
          200
        );
```

2021-10-25 06:37 UTC, tephenavies commented on lib/ReactViews/Map/Panels/SharePanel/PrintView.tsx
>          );
Also needs method binding

2021-10-25 06:37 UTC, tephenavies commented on lib/ReactViews/Map/Panels/SharePanel/PrintView.tsx
> +  create(options: CreateOptions) {
This should be exported separately (or, if necessary made a `static` function, but a separate export sounds better to me). I get this error in CI:
```
Uncaught TypeError: _PrintView.default.create is not a function
    createPrintView SharePanel.jsx:230
    showPrintView SharePanel.jsx:216
```

2021-10-25 06:37 UTC, tephenavies commented on lib/ReactViews/Map/Panels/SharePanel/PrintView.tsx
> -  },
I can't find where attribution is dealt with now. Chances are this workaround is not needed any more since we don't support IE11 and I'm 99.9% sure the Edge that doesn't work is the pre-chromium one that we also don't support.

2021-10-25 06:37 UTC, tephenavies commented on lib/ReactViews/Map/Panels/SharePanel/PrintView.tsx
> +  renderLegend(catalogItem: any) {
Even if we do need to use `any`, I prefer to add one or more strongly typed type first. Like:
```suggestion
  renderLegend(catalogItem: MappableMixin.Instance | BaseModel | any) {
```
Although this won't throw type errors for bad usage, it enables IDE features like auto complete, and also "Get References" on any MappableMixin.Instance properties/functions used.

The type signature I suggested is only an example. Let me know if you want help working out an appropriate one.

2021-10-25 06:37 UTC, tephenavies commented on lib/ReactViews/Map/Panels/SharePanel/PrintView.tsx
> +      printWindow = window.open(),
I did not know that you can put side effects in defaults when using object destructuring. I know this is in the previous version too, but it's a TIL for me. I guess the behaviour has to match default parameters because object destructuring should be semantically the same whether it's used in function parameters or with `const`.

2021-11-15 01:39 UTC, wibily commented
latest branch is wc-preportal

2021-12-20 01:25 UTC, steve9164 commented
I think this is still in draft stage. Please let me know if that's wrong.

2021-12-20 01:26 UTC, closed without merging