Wc print2
TerriaJS/terriajs pull request #6099
Opened 2022-01-20 11:02 UTC by wibily

### Make print preview work a bit better

## Features:
- React portal into new window allows usage of styled components
- Scale is scaled from parent map
- Will correctly show which SelectableDimension is selected and displayed on the map
- Collapsable/Expandable datasets

## To test:
Go to http://ci.terria.io/wc-print2/
Add in map data from explore map data button
Go to Share/Print button in the top right
Click on Show print preview

### Checklist

-   [ x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ x] I've updated relevant documentation in `doc/`. N/A
-   [ x] I've updated CHANGES.md with what I changed.
-   [x ] I've provided instructions in the PR description on how to test this PR.

2022-01-21 05:33 UTC, nf-s requested changes
Looking good!

Just a few type-related suggestions.

Also, the map screenshot doesn't update if there is an existing window.

To recreate:
- Click Share/Print
- Leave tab open
- Click Share/Print again

2022-01-21 05:33 UTC, nf-s commented on CHANGES.md
> +* TSXified PrintView
This should be under `next release (8.1.18)`

2022-01-21 05:33 UTC, nf-s commented on lib/Models/SelectableDimensions.ts
> +  readonly options?: readonly option<any>[];
I think this can be `string`. If not, maybe create generic type in `SelectableDimensionSelect`

```suggestion
  readonly options?: readonly option<string>[];
```

2022-01-21 05:33 UTC, nf-s commented on lib/Models/SelectableDimensions.ts
> +};
I like these 👍

2022-01-21 05:33 UTC, nf-s commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintDatasets.tsx
> +  items: readonly (CatalogMemeberMixin.Instance & BaseModel & any)[];
```suggestion
  items: readonly BaseModel[];
```

2022-01-21 05:33 UTC, nf-s commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintDatasets.tsx
> +          <summary>{item.name}</summary>
There is a `getName` function which takes `BaseModel` and tries to find best name property.

```suggestion
          <summary>{getName(item)}</summary>
```

2022-01-21 05:33 UTC, nf-s commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintDatasets.tsx
> +import CatalogMemeberMixin from "../../../../../ModelMixins/CatalogMemberMixin";
```suggestion
import { getName } from "../../../../../ModelMixins/CatalogMemberMixin";
```

2022-01-21 05:33 UTC, nf-s commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintDatasets.tsx
> +import CatalogMemeberMixin from "../../../../../ModelMixins/CatalogMemberMixin";
Needed for change below

2022-01-21 05:33 UTC, nf-s commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintView.tsx
> +          <PrintSource link={buildShareLink(props.terria, props.viewState)} />
Here we should use `buildShortShareLink` if possible.

For example see

https://github.com/TerriaJS/terriajs/blob/7e0f5f594a5c5bcf57f1490792e22c1b20bda221/lib/Models/sendFeedback.ts#L32-L36

2022-01-21 05:33 UTC, nf-s commented on package.json
> -    "create-react-class": "^15.6.2",
🎉

2022-01-21 05:33 UTC, nf-s commented on package.json
> -    "create-react-class": "^15.6.2",
Bonus points for removing dep

2022-01-21 05:33 UTC, nf-s commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintWorkbench.tsx
> +const renderDisplayVariables = (catalogItem: BaseModel & any) => {
Can we get rid of the `any` here?

```suggestion
const renderDisplayVariables = (catalogItem: BaseModel) => {
```

2022-01-21 05:33 UTC, nf-s commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintWorkbench.tsx
> +const WorkbenchItem = ({ item }: { item: BaseModel | any }) => {
```suggestion
const WorkbenchItem = ({ item }: { item: BaseModel }) => {
```

2022-01-21 05:33 UTC, nf-s commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintWorkbench.tsx
> +    any
```suggestion
  catalogItem: BaseModel
```

2022-01-21 05:33 UTC, nf-s commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintWorkbench.tsx
> +  if (!catalogItem.isMappable) {
```suggestion
  if (!MappableMixin.isMixedInto(catalogItem)) {
```

2022-01-21 05:33 UTC, nf-s commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintWorkbench.tsx
> +      {catalogItem.currentTime && (
```suggestion
      {DiscretelyTimeVaryingMixin.isMixedInto(catalogItem) && (
```

2022-01-24 23:54 UTC, wibily commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintDatasets.tsx
> +          <summary>{item.name}</summary>
Thanks, i didn't know about that function. It makes tightening up the types a lot easier

2022-01-24 23:55 UTC, wibily commented on lib/ReactViews/Map/Panels/SharePanel/Print/PrintWorkbench.tsx
> +const renderDisplayVariables = (catalogItem: BaseModel & any) => {
yup, will do

2022-01-25 02:45 UTC, nf-s approved these changes
Looks good!

A few small things - I realise this is not the final version - so feel free to respond to them in another PR:

1. Time format is not great
2. Dealing with scale in 3D mode is hard, not sure how best to do it. In this example the camera angle is quite low, so scale will change a lot from bottom of the map to the top. Maybe it is better to not show a scale if there is large variation across the map?
3. There are some `Collapsible` caret icon things missing here
4. The share link doesn't update when you re-generate the Print view if there is an existing window

![Screen Shot 2022-01-25 at 1 38 23 pm](https://user-images.githubusercontent.com/6187649/150900946-69d2f4e7-c535-42ae-bc48-b0d3d125b5c3.png)

2022-01-25 02:48 UTC, merged

2022-01-25 02:55 UTC, wibily commented
thanks for the detailed review:
1) Yeah, agreed. I'll make a note of it in the main ticket
2) I'm using the same component for the scale as the one in the main viewer so i think we'll need to figure out that problem holistically. I'm not sure what the best solution is either :/
3) Yup, the whole expandable items section needs a bit more work. Right now i'm just using the default HTML <summary> and <detail> elements
4. Nice catch, i missed that