ArcGisFeatureServerCatalogItem can now load more features
TerriaJS/terriajs pull request #6139
Opened 2022-02-14 06:23 UTC by KeyboardSounds

### What this PR does

Fixes #<insert issue number here if relevant>

ArcGisFeatureServerCatalogItem can now load more than the maximum feature limit set by the server by making multiple requests, and uses GeojsonMixin
  
### Test me
  
How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [ ] I've updated CHANGES.md with what I changed.
-   [ ] I've provided instructions in the PR description on how to test this PR.

2022-02-22 01:26 UTC, rowanwins commented on lib/Models/Catalog/Esri/ArcGisFeatureServerCatalogItem.ts
> +        .addQuery("orderByFields", "OBJECTID")
Rather than hardcoding this it can be read from the service metadata as the `objectIdField`.

2022-02-22 01:44 UTC, rowanwins commented on lib/Models/Catalog/Esri/ArcGisFeatureServerCatalogItem.ts
> +      .addQuery("layerDefs", `{"${layerId}": "${this.layerDef}"}`)
Think this `layersDefs` is redundant given the `where` query above.

2022-02-22 01:44 UTC, rowanwins commented on lib/Models/Catalog/Esri/ArcGisFeatureServerCatalogItem.ts
> +      .addQuery("where", "1=1")
The `1=1` should probably Although the where should probably equal the `layerDef` trait

2022-03-03 10:10 UTC, nf-s requested changes

2022-03-03 10:10 UTC, nf-s commented on lib/ModelMixins/GeojsonMixin.ts
> +      }
```suggestion
      } catch (e) {
        TerriaError.from(e, "Failed to create `rectangle` for GeoJSON").log();
      }
```

2022-03-03 10:10 UTC, nf-s commented on lib/Models/Catalog/Esri/ArcGisFeatureServerCatalogItem.ts
>      }
This should be in `FeatureServerStratum.shortReport`

2022-03-03 10:10 UTC, nf-s commented on lib/Models/Catalog/Esri/ArcGisFeatureServerCatalogItem.ts
> +    entities.suspendEvents();
Does it matter that all the ESRI styling is going to be applied on top of GeoJsonMixin styling for each entity?

Would it be better to call `GeoJsonDataSource.load(...)` separately and apply ESRI styling on "clean" entities?

2022-03-09 06:43 UTC, nf-s approved these changes

2022-03-10 01:45 UTC, merged