Fix terrain load order in Cesium viewer.
TerriaJS/terriajs pull request #6460
Opened 2022-07-26 07:22 UTC by na9da

The change gives highest priority to the first terrain in workbench or overlays.

### What this PR does

Fixes #<insert issue number here if relevant>

This is a description of what I've done in this PR, especially explaining choices made to make the reviewer's job easier. If I don't replace this paragraph with an actual description, my PR will probably be ignored.
  
### Test me
  
How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [ ] I've updated CHANGES.md with what I changed.
-   [ ] I've provided instructions in the PR description on how to test this PR.

2022-07-27 08:07 UTC, steve9164 requested changes
Looks good. Just a couple of changes needed

2022-07-27 08:07 UTC, tephenavies commented on lib/Models/Catalog/CatalogItems/CesiumTerrainCatalogItem.ts
> +      : Promise.reject("Failed to load terrain provider");
Please wrap this string in a `new Error` or `TerriaError`.

2022-07-27 08:07 UTC, tephenavies commented on lib/Models/Catalog/CatalogItems/CesiumTerrainCatalogItem.ts
> +  > {
Please remove the action decorator so that property access is tracked.

2022-07-27 23:46 UTC, na9da commented on lib/Models/Catalog/CatalogItems/CesiumTerrainCatalogItem.ts
> +  > {
Good catch! I always forget that `forceLoadMapItems` runs inside a `computed`!

2022-07-27 23:47 UTC, na9da commented
@steve9164 - Thanks for the feedback. I resolved your change requests and made one additional change to `shortReport` so that it doesn't override a trait setting.

2022-07-29 05:01 UTC, steve9164 approved these changes

2022-07-29 05:07 UTC, merged