Help video changes
TerriaJS/terriajs pull request #6480
Opened 2022-08-05 01:34 UTC by na9da

### What this PR does

* Add `videoCoverImageOpacity` option to `HelpContentItem` so that we can fade the background of help video panels.
* Fix a bug where all `HelpVideoPanel`s were being rendered simultaneously resulting in autoplayed videos playing at random.

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [x] I've updated CHANGES.md with what I changed.
-   [x] I've provided instructions in the PR description on how to test this PR.

2022-08-05 01:37 UTC, na9da commented on lib/ReactViews/Map/Panels/HelpPanel/HelpVideoPanel.jsx
> +      itemSelected && <div className={className}>
Render this component only when it is selected. Not really sure why it was implemented this way. In my testing with videos that have autoplay enabled, this resulted in the user clicking one video but another video gets played.

2022-08-05 17:27 UTC, steve9164 requested changes, later dismissed

2022-08-05 17:27 UTC, steve9164 commented on lib/ReactViewModels/defaultHelpContent.ts
> +  videoCoverImageOpacity?: boolean;
Should be `number`

2022-08-07 23:37 UTC, na9da commented on lib/ReactViewModels/defaultHelpContent.ts
> +  videoCoverImageOpacity?: boolean;
Ah yes!

2022-08-08 03:04 UTC, mwu2018 commented
I've verified it with `dev` site.

2022-08-08 03:04 UTC, mwu2018 approved these changes

2022-08-08 03:07 UTC, merged