Tsify map column
TerriaJS/terriajs pull request #6494
Opened 2022-08-08 09:15 UTC by zoran995

### What this PR does

Fixes #<insert issue number here if relevant>

Tsify `MapColumn`, `TerriaViewerWrapper`, `LocationBar`, `DistanceLegend`, `Splitter`.
  
### Test me
  
How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

-   [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
-   [ ] I've updated relevant documentation in `doc/`.
-   [ ] I've updated CHANGES.md with what I changed.
-   [ ] I've provided instructions in the PR description on how to test this PR.

2022-08-29 13:25 UTC, steve9164 commented
Whoops. I messed up the post-prettier tag merge. Fixing it now.

2022-08-29 13:35 UTC, steve9164 commented
Hopefully fixed. Sorry about that. I was just testing some instructions I'm going to post to the discussions forum and missed a step.

2023-05-04 11:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TerriaJS/terriajs?pullRequest=6494) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/TerriaJS/terriajs?pullRequest=6494) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: zoran995<br/>:white_check_mark: steve9164<br/>:x: Zoran Kokeza<br/><hr/>**Zoran Kokeza** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TerriaJS/terriajs?pullRequest=6494) it.</sub>

2023-05-24 00:24 UTC, staffordsmith83 commented
@staffordsmith83 to assess this and the time it will take this sprint

2023-07-14 05:39 UTC, staffordsmith83 commented
@zoran995 Ill push this to a new branch on `terriajs` repo and work on it there if thats ok? Just merging in latest main etc

2023-07-17 11:17 UTC, zoran995 commented
@staffordsmith83 of course, also you feel free to push it directly to this branch if you want

2023-07-18 07:22 UTC, staffordsmith83 requested changes
## ProgressBar.tsx

ProgressBar.tsx is good, made a couple of small changes
- css wrapper on line 73
- mode:boolean on line 19
- added `terria.baseMapContrastColor` to dependencies array on line 40



## MapColumn.tsx

You have removed `chromeVersion` checking stuff. Is this no longer necessary?

`customFeedbacks` declared in props but not used. Reimplement the section from MapColumn.jsx that is commented out in latest main?

`MapColumn` now includes `ProgressBar` - where was it before? In `StandardUserInterface` - why is this moved?

// @ts-ignore on line 59, can we fix this?



Is this functionality retained somewhere? ln 67-69 in MapColumn.jsx in main
```
css={`
${this.props.viewState.explorerPanelIsVisible &&
"opacity: 0.3;"}
`}
```


FeedbackItem display has been removed
In MapColumn.jsx this was https://github.com/TerriaJS/terriajs/blob/f62bfafb3919ed8ac0499b32c9e0e30e9f3b16dc/lib/ReactViews/StandardUserInterface/MapColumn.jsx#L167-L173


Line 123 the condition used to be `If condition={!this.props.viewState.hideMapUi}`
Do we need to put this back in?


## Compass.tsx
Improper find and replace?

"the way our compass is composed" became
"the way our compassbase is composed"

and in a few other places.



## Other changes
Moves `MapCredits` out of `StandardUserInterface` and into `MapColumn` - I think this is fine

## SUMMARY
There is some great workhere Zoran to neaten up a lot of things, I have really noticed your work. Replacing  passing viewstate and terria in props with hooks, restructuring the code, and the complex work of rewriting key files in TS. We are VERY grateful for your work and sorry that it has taken so long to review. Please have a look at these few things and we hope to merge soon!

2023-07-18 08:47 UTC, zoran995 commented
- for the Chrome version my understanding is that it is no longer needed. The underlying bug was resolved 4 years ago in modern development it is like supporting IE 🙂
- The commented-out code for the feedback button in my understanding was only to render the feedback button in the right part of the map. Still, this part is completely reworked and reimplemented as part of map navigation. 
- I am unsure how to render the custom feedback part (feedback item) and in which case they should be visible. Do you have a way to show them in the current main? If we don't have it then I can just put it there blindly and hope it works correctly. The prop could be deleted as it is just reading a value from `customElements` which is already sent to `MapColumn`. Honestly, I completely missed that part I thought that it is somehow related to the button implementation above.
- `ProgressBar` move - it's really a long time since I've done this so I don't recall but probably some element stacking or css simplification. And based on the old `StandardUserInterface` it is already in `MapColumn` section and it was connected to it
- Good catch for removed css opacity it should be restored 👍 
- Good catch for Line 123 👍

2023-07-20 02:12 UTC, staffordsmith83 commented
Hi @zoran995 thanks again for your quick response! 

OK for points 1,2, and 4.
Regarding point 3, @Nanda can you answer zorans question for "I am unsure how to render the custom feedback part (feedback item) and in which case they should be visible. Do you have a way to show them in the current main? If we don't have it then I can just put it there blindly and hope it works correctly. The prop could be deleted as it is just reading a value from customElements which is already sent to MapColumn. Honestly, I completely missed that part I thought that it is somehow related to the button implementation above."
The context for this is in the PR review if that doesnt make sense!

@zoran995 would you like to implement the last two points, or should I?

2023-08-02 03:14 UTC, staffordsmith83 commented
> Hi @zoran995 thanks again for your quick response!
> 
> OK for points 1,2, and 4. Regarding point 3, Ive checked with the team and we are no longer using `customFeedback` so dont worry about this, Ill make a separate issue to clean up all refs to it :-)
> 
> @zoran995 would you like to implement the last two points, or should I?

I have implemented those last two changes, I think this is ready to merge @steve9164

2023-08-02 03:25 UTC, staffordsmith83 approved these changes
All required changes implemented

2023-08-02 04:35 UTC, staffordsmith83 commented
@steve9164 to review before merging

2023-09-07 06:59 UTC, staffordsmith83 commented
@steve9164 any luck with this? Keen to help if you need

2023-09-11 01:26 UTC, steve9164 approved these changes

2023-09-11 04:06 UTC, nf-s requested changes

2023-09-11 04:06 UTC, nf-s commented on CHANGES.md
> +- [The next improvement]
Hey @steve9164 and @staffordsmith83 

Before this is merged in can you please update the `CHANGES` file here. Thanks!

2023-09-11 11:47 UTC, nf-s approved these changes
Done thanks @zoran995 !

2023-09-11 23:47 UTC, staffordsmith83 commented
URGENT: before merging this let me check that this is the right PR with the changes I made for Zoran

2023-09-11 23:55 UTC, staffordsmith83 commented
All good, ready to merge

2023-09-12 00:31 UTC, merged