Add ActionBar.
TerriaJS/terriajs pull request #6645
Opened 2022-12-02 02:56 UTC by na9da

### What this PR does
Required for https://github.com/TerriaJS/nsw-digital-twin/issues/567

- A new floating menu at the bottom of the map that looks like:
  ![image](https://user-images.githubusercontent.com/1430/205204505-f1d333aa-222a-4df6-a452-acc833606516.png)
  This will be used by the SceneEditor, but other plugins can also make use of it.
- Refactors some of the Portal code in Terria

### Test me

The `ActionBar` is currently not used by any feature in core Terria, so it cannot be tested from the CI. 

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

2022-12-02 03:05 UTC, na9da commented on lib/Styled/Button.tsx
> +            }
Previously, a margin used to be shown even when the contents where empty, this bloated the buttons that only had an Icon and no text. This fixes it.

2023-01-04 01:51 UTC, steve9164 requested changes

2023-01-04 01:51 UTC, steve9164 commented on lib/ReactViews/ActionBar/ActionBarPortal.tsx
> +export default withViewState(ActionBarPortal);
Prefer use of `useViewState` and reduce passing viewState through props to reduce noise. Could you update StandardUserInterface/Portal to use `useViewState`? Then I think you won't need viewState here.

2023-01-04 01:51 UTC, steve9164 commented on lib/ReactViews/Workflow/WorkflowPanelPortal.tsx
> +export default withViewState(WorkflowPanelPortal);
I think this `withViewState` also can be removed when Portal uses useViewState.

2023-01-05 03:46 UTC, na9da commented
Thanks for the feedback @steve9164! I have updated the code to replace explicit `viewState` props with `useViewState()` hook.

2023-01-05 05:33 UTC, steve9164 approved these changes
Thanks @na9da!

2023-01-05 05:35 UTC, steve9164 commented
Actually, should there be a changelog entry in this PR, or is it included in a different PR?

2023-01-05 05:48 UTC, na9da commented
Thanks @steve9164! 

> Actually, should there be a changelog entry in this PR, or is it included in a different PR?

I have updated the changelog in the latest commit. Kept it for last to avoid frequent merge conflicts.

2023-01-05 06:06 UTC, merged