Add EPSG:7844 to fix ideal zoom for esri mapserver item.
TerriaJS/terriajs pull request #6736
Opened 2023-03-20 22:19 UTC by na9da

### What this PR does

Fixes #6590 

- Adds proj4 definition for EPSG:7844 to Terria
  This is required to fix #6590.
- Converted modules `Proj4Defintions` and `Reproject` to Typescript.
- Enable spec for Reproject module.

### Test me

- Open this CI link for [main branch](http://ci.terria.io/main/#share=s-dpFrV1KOQnCzf8KVQBXQeSlfdu)
- Observe that the `Ideal zoom` workbench feature doesn't work for any of the dataset.
- Now open CI for this branch.
- Observe that the `Ideal zoom` is now fixed.

### Checklist

- [x] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [x] I've provided instructions in the PR description on how to test this PR.

2023-03-20 22:21 UTC, na9da commented on lib/Map/Vector/Proj4Definitions.ts
> +  "EPSG:7844": "+proj=longlat +ellps=GRS80 +no_defs +type=crs"
New addition.

2023-03-20 22:21 UTC, na9da commented on lib/Map/Vector/Reproject.ts
TSified.

2023-03-20 22:22 UTC, na9da commented on lib/ModelMixins/GeojsonMixin.ts
Type fixes after TSifying `Reproject` module.

2023-03-20 22:23 UTC, na9da commented on test/ViewModels/UploadDataTypesSpec.ts
> +describe("UploadDataTypes", function () {
Fix accidental commit from a previous PR.

2023-04-20 04:55 UTC, mwu2018 requested changes
Looks good. Very minor changes might be required.

2023-04-20 04:55 UTC, mwu2018 commented on lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts
> +    if (!isDefined((Proj4Definitions as any)[wkid])) {
`(Proj4Definitions as any)[wkid]` can be simplified as `Proj4Definitions[wkid]`. The same to the rest.

2023-04-20 05:43 UTC, mwu2018 approved these changes

2023-04-21 01:36 UTC, merged