Fix rectangle drawing in 2D mode
TerriaJS/terriajs pull request #6855
Opened 2023-08-28 08:47 UTC by na9da

### What this PR does

Fixes #6853 

Currently the rectangle drawing like the one drawn when exporting a portion of the imagery layer is broken in 2D mode. This PR fixes it.

### Test me

- Open [this CI link](http://ci.terria.io/main/#configUrl=https://terria-catalogs-public.storage.googleapis.com/geo-rapp/map-config/prod.json&share=s-nZWndrSs6NFPi160eCRDBYBw3A5) for `main` branch, try out the `Export` option for the workbench item
- Notice that in 3D mode, a rectangle is rendered on the map to show the drawn region
- Notice that this doesn't happen in 2D mode.
- Now try the same with [this branch](http://ci.terria.io/fix-2d-rectangle-drawing/#configUrl=https://terria-catalogs-public.storage.googleapis.com/geo-rapp/map-config/prod.json&share=s-nZWndrSs6NFPi160eCRDBYBw3A5).

Before:

After:

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

2023-08-28 22:36 UTC, na9da commented on lib/ReactViewModels/MouseCoords.ts
> -    coordinates.height = <any>undefined;
Setting `height` as `undefined` resulted in some computations producing `NaN` values which broke the rectangle drawing.

2023-08-30 05:37 UTC, nf-s requested changes
3D Terrain and 2D modes are working perfectly, but I am having an issue with 3D Smooth mode, when I try to draw a rectangle extent, I get the following error on the first click

<img width="1052" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/7dc3fbee-1c95-4e97-b65b-76338fe75622">

This may be out-of-scope of this PR - if so, let me know and I'll make a ticket 🙂

2023-08-31 04:03 UTC, na9da commented
There was a similar issue in ellipsoidal terrain mode. I have fixed it now - should work once the CI instance is updated.

![image](https://github.com/TerriaJS/terriajs/assets/1430/f7b0f169-6f37-4643-84ea-b7400f2e0947)

2023-08-31 05:27 UTC, nf-s approved these changes
Great, thanks!

2023-09-03 23:55 UTC, na9da commented
Thanks @nf-s

2023-09-03 23:56 UTC, merged