Wps default date
TerriaJS/terriajs pull request #7026
Opened 2024-01-10 06:52 UTC by sixlighthouses

### What this PR does

Fixes #<insert issue number here if relevant>

This is a description of what I've done in this PR, especially explaining choices made to make the reviewer's job easier. If I don't replace this paragraph with an actual description, my PR will probably be ignored.

### Test me

How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

2024-03-08 04:33 UTC, sppigot commented
@sixlighthouses - Thanks for your work on this!

Testing with no timeline:

- Default date/time does get set to current date/time in wps parameter form
- Manually changing dates or times works correctly

However, when if I set dates/times and then click on the map to get a location, the dates and times seem to be reset to the current date/time when the form reappears. Changing them back to what I had before seems to work but when I submit the form the start date/time value is messed up in the request that goes to the WPS:

e.g. 
![messedupdatetime](https://github.com/TerriaJS/terriajs/assets/1842016/87c39a59-c4f7-4ff7-a724-c689afd330cb)

Testing with timeline shortly.

2024-03-08 04:58 UTC, sppigot commented
@sixlighthouses - testing with a timeline - the default date does get set to the currently selected value in the timeline but seems to be off by 1 day for some reason? (Am I missing something obvious here?). Check the following image:

![offby1day](https://github.com/TerriaJS/terriajs/assets/1842016/a1efbe67-609a-455b-9676-0a40947872ee)

Thanks for your work on this @sixlighthouses !

2024-03-19 01:16 UTC, sixlighthouses commented
@sppigot thanks for test and the feedback.  I have made some updates so when you get a chance please review again

2024-05-03 00:39 UTC, na9da requested changes
@sixlighthouses I think these changes look great. Thanks for taking time to refactor the component as `tsx`. 

I have just left a couple of comments.

2024-05-03 00:39 UTC, na9da commented on CHANGES.md
> +- [The next improvement]
I think these need to go.

2024-05-03 00:39 UTC, na9da commented on lib/ReactViews/Analytics/DateTimeParameterEditor.tsx
> +  }, [parameter, terria.timelineStack.clock.currentTime]);
It is more correct to depend on `parameter.value` instead?

2024-05-03 01:05 UTC, na9da commented on lib/ReactViews/Analytics/DateTimeParameterEditor.tsx
> +  }, [parameter, terria.timelineStack.clock.currentTime]);
On further thought, that could lead to an infinite loop.

2024-05-03 02:01 UTC, na9da approved these changes
Looks good!

2024-05-26 23:49 UTC, merged