Feature info chart fixes.
TerriaJS/terriajs pull request #7156
Opened 2024-05-14 07:23 UTC by na9da

### What this PR does

Alternate approach to https://github.com/TerriaJS/terriajs/pull/6960 for making y-column of feature info charts configurable.

This is a description of what I've done in this PR, especially explaining choices made to make the reviewer's job easier. If I don't replace this paragraph with an actual description, my PR will probably be ignored.

### Test me

How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

2024-05-20 07:00 UTC, mwu2018 commented
@na9da  I've verified the above testing examples. Also have verified with my own datasets. They all work nicely.

2024-05-21 02:02 UTC, na9da commented on lib/ModelMixins/TableMixin.ts
>            }
Same as before but just convinces TS that value is not `undefined` when using `yColumnId` below.

2024-05-21 02:03 UTC, na9da commented on lib/ReactViews/Custom/Chart/ChartExpandAndDownloadButtons.tsx
Use styled-components.

2024-05-21 02:04 UTC, na9da commented on lib/ReactViews/Custom/ChartCustomComponent.ts
> +          yColumn: attrs.yColumns?.[0],
Pass `y-column` as prop to the `FeatureInfoPanelChart`

2024-05-22 07:29 UTC, nf-s requested changes
I feel like adding a `y-column` to `FeatureInfoPanelChart` kind of skips the `TableStyle` system. This behaviour is different from `ChartView`/`ChartPanel` - which uses  `ChartItem.showChartInPanel` to determine which charts should be showing.

Ideally `CsvChartCustomComponent` `y-columns` attribute is used to set `TableChartLineStyleTraits.isSelectedInWorkbench` - and then `FeatureInfoPanelChart` shows the first applicable chart item.

What do you think?

2024-05-22 07:35 UTC, nf-s commented
I also wonder if it is worth reverting

- https://github.com/TerriaJS/terriajs/pull/6960

if it is no longer needed here - as this was the only use of `MergeStrategy.TopStratum`. How strata is merged is hairy, and I'm not convinced that it was the best approach - it might be better to visit the problem more holistically later

2024-05-23 06:15 UTC, nf-s approved these changes
After discussion: it is difficult to do what I suggested - so merge this in as short-term solution

2024-05-27 01:58 UTC, na9da commented
For more context, the reason why we are not able to implement the recommended fix to use `isSelectedInWorkbench` trait is that isSelectedInWorkbench is set to true here for the first column:
https://github.com/TerriaJS/terriajs/blob/b73909e26f7193d9047a1460dcab559f3a3e9336/lib/Table/TableAutomaticStylesStratum.ts#L162-L165

To override that programmatically, we'll need to know what columns exists, but that is not known until the chart catalog item is loaded [here in FeatureInfoPanelChart](https://github.com/TerriaJS/terriajs/blob/e3ad3cbdc84b802412c83369f28ef72b9c616488/lib/ReactViews/Custom/Chart/FeatureInfoPanelChart.tsx#L81). It is easier then, to just pass the chosen `y-column` as a prop.

2024-05-28 05:29 UTC, merged