Cog support cesium only 1
TerriaJS/terriajs pull request #7209
Opened 2024-06-21 03:02 UTC by staffordsmith83

### What this PR does

Fixes #<insert issue number here if relevant>

This is a description of what I've done in this PR, especially explaining choices made to make the reviewer's job easier. If I don't replace this paragraph with an actual description, my PR will probably be ignored.

### Test me

How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

2024-06-25 07:48 UTC, nf-s reviewed
Awesome stuff, thanks @staffordsmith83 !

I haven't finished my review yet - but thought I should post what I have

Did we end up deciding how to handle projections that aren't cesium native (wgs84 and webmercator)?

If are going to allow reprojection, I think we should add a "short report" so there's a message in the workbench. As it looks like there are some reprojection issues

<img width="1279" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/1fc9c5c7-b680-4844-a484-e5ea009c7b5b">

- [Reprojection example - epsg:32756](http://ci.terria.io/cog-support-cesium-only-1/#clean&https://gist.githubusercontent.com/staffordsmith83/9a6ba12479100a810dadcf0119242913/raw/d1c0fdf888e8477be8f044721b7cd1e2ec33c907/cogs_three_groups.json&start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22%2F%2FSupported+Datasets%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2F%2FSupported+Datasets%2FCOG+Test+Whian+Whian%22%3A%7B%22opacity%22%3A1%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%2FSupported+Datasets%22%5D%2C%22type%22%3A%22cog%22%7D%2C%22%2F%22%3A%7B%22type%22%3A%22group%22%7D%7D%2C%22workbench%22%3A%5B%22%2F%2FSupported+Datasets%2FCOG+Test+Whian+Whian%22%5D%2C%22timeline%22%3A%5B%5D%2C%22initialCamera%22%3A%7B%22west%22%3A153.41161478960097%2C%22south%22%3A-28.061298397857612%2C%22east%22%3A153.42650335865278%2C%22north%22%3A-28.042438926989824%2C%22position%22%3A%7B%22x%22%3A-5039055.0838929955%2C%22y%22%3A2521274.6258177627%2C%22z%22%3A-2982430.527881199%7D%2C%22direction%22%3A%7B%22x%22%3A0.7892395196302652%2C%22y%22%3A-0.3948933959656323%2C%22z%22%3A0.47027671266661586%7D%2C%22up%22%3A%7B%22x%22%3A-0.4205699368373914%2C%22y%22%3A0.21043078364419832%2C%22z%22%3A0.8825190159557363%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22viewerMode%22%3A%223dSmooth%22%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.4999%2C%22settings%22%3A%7B%22baseMaximumScreenSpaceError%22%3A2%2C%22useNativeResolution%22%3Atrue%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-positron%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse%7D%2C%22stories%22%3A%5B%5D%7D%5D%7D)
- [uluru reprojection example](http://ci.terria.io/cog-support-cesium-only-1/#clean&https://gist.githubusercontent.com/staffordsmith83/9a6ba12479100a810dadcf0119242913/raw/d1c0fdf888e8477be8f044721b7cd1e2ec33c907/cogs_three_groups.json&start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22%2F%2FSupported+Datasets%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2F%2FSupported+Datasets%2FCOG+Test+Whian+Whian%22%3A%7B%22opacity%22%3A1%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%2FSupported+Datasets%22%5D%2C%22type%22%3A%22cog%22%7D%2C%22%2F%2FSupported+Datasets%2FUSGS+Elevation%22%3A%7B%22opacity%22%3A1%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%2FSupported+Datasets%22%5D%2C%22type%22%3A%22cog%22%7D%2C%22%2F%2FSupported+Datasets%2FCOG+Test+Uluru%281%29%22%3A%7B%22knownContainerUniqueIds%22%3A%5B%22%2F%2FSupported+Datasets%22%5D%2C%22type%22%3A%22cog%22%7D%2C%22%2F%22%3A%7B%22type%22%3A%22group%22%7D%7D%2C%22workbench%22%3A%5B%22%2F%2FSupported+Datasets%2FCOG+Test+Uluru%281%29%22%5D%2C%22timeline%22%3A%5B%5D%2C%22initialCamera%22%3A%7B%22west%22%3A130.5873113853551%2C%22south%22%3A-25.81071236732281%2C%22east%22%3A130.59992099929624%2C%22north%22%3A-25.794414151922386%2C%22position%22%3A%7B%22x%22%3A-3739698.691339093%2C%22y%22%3A4364165.316830322%2C%22z%22%3A-2760066.4969194573%7D%2C%22direction%22%3A%7B%22x%22%3A0.585815228580093%2C%22y%22%3A-0.683636494180984%2C%22z%22%3A0.43527194004160996%7D%2C%22up%22%3A%7B%22x%22%3A-0.2832269316883932%2C%22y%22%3A0.33052105372270196%2C%22z%22%3A0.9002990271084452%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22viewerMode%22%3A%223dSmooth%22%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.5%2C%22settings%22%3A%7B%22baseMaximumScreenSpaceError%22%3A2%2C%22useNativeResolution%22%3Atrue%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-positron%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse%7D%2C%22stories%22%3A%5B%5D%7D%5D%7D)

I actually think we should disable reprojection until we fully understand how it works - and can validate that it is accurate enough for visualisation purposes - I think it is doing some weird stuff on the edges of tiles - especially when using nearest pixel interpolation.

There are also some tiling and pixel interpolation issues with the 4326 COG

- [open aerial map example](http://ci.terria.io/cog-support-cesium-only-1/#clean&https://gist.githubusercontent.com/staffordsmith83/9a6ba12479100a810dadcf0119242913/raw/d1c0fdf888e8477be8f044721b7cd1e2ec33c907/cogs_three_groups.json&start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22%2F%2FSupported+Datasets%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2F%2FSupported+Datasets%2FDrone+image+from+Open+Aerial+Map%22%3A%7B%22knownContainerUniqueIds%22%3A%5B%22%2F%2FSupported+Datasets%22%5D%2C%22type%22%3A%22cog%22%7D%2C%22%2F%22%3A%7B%22type%22%3A%22group%22%7D%7D%2C%22workbench%22%3A%5B%22%2F%2FSupported+Datasets%2FDrone+image+from+Open+Aerial+Map%22%5D%2C%22timeline%22%3A%5B%5D%2C%22initialCamera%22%3A%7B%22west%22%3A-90.8706279985145%2C%22south%22%3A14.589539101881737%2C%22east%22%3A-90.8702281108131%2C%22north%22%3A14.590095198398252%2C%22position%22%3A%7B%22x%22%3A-93788.20540361805%2C%22y%22%3A-6173117.815926865%2C%22z%22%3A1596232.9717276145%7D%2C%22direction%22%3A%7B%22x%22%3A0.014701393256942266%2C%22y%22%3A0.9676422770093419%2C%22z%22%3A-0.2518973854181122%7D%2C%22up%22%3A%7B%22x%22%3A0.0038266364342477723%2C%22y%22%3A0.25186831804353843%2C%22z%22%3A0.9677539497307769%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22viewerMode%22%3A%223dSmooth%22%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.4999%2C%22settings%22%3A%7B%22baseMaximumScreenSpaceError%22%3A2%2C%22useNativeResolution%22%3Atrue%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-positron%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse%7D%2C%22stories%22%3A%5B%5D%7D%5D%7D)

This example gets much better when the `TextureMagnificationFilter` is set to `Nearest` instead of the default `Linear` value - I think we should change the default to `Nearest` (see comment below)

## On texture filters + pixel interpolation

### Reprojection example

<img width="2559" alt="Screenshot 2024-06-25 at 5 02 57 PM" src="https://github.com/TerriaJS/terriajs/assets/6187649/ad5b68a8-391b-49a7-b649-4eb2412924da">

### 4326 example

<img width="2560" alt="Screenshot 2024-06-25 at 5 25 38 PM" src="https://github.com/TerriaJS/terriajs/assets/6187649/a6a0ad36-6f1f-40d2-b32e-2cbf9ae6f099">

<img width="2558" alt="Screenshot 2024-06-25 at 5 44 00 PM" src="https://github.com/TerriaJS/terriajs/assets/6187649/022a8905-1c5b-460e-9434-5908dabd2ff1">

I'm a bit confused why the "linear pixel interpolation with nearest filter" looks so weird - why are the pixels that shape?

This is what the data looks like in QGIS (with web mercator projection)

<img width="1276" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/6b706915-dc38-4f81-a78f-c01e33862fbe">

I would expect a 4326 COG to look basically perfect in cesium

### Web mercator example

I need to find an example to use here

2024-06-25 07:48 UTC, nf-s commented on lib/Models/Terria.ts
> +  proj4ServiceBaseUrl: string;
I think this should stay optional here - if people want to disable it

2024-06-25 07:48 UTC, nf-s commented on lib/Traits/TraitsClasses/CogRenderOptionsTraits.ts
> +}
Feel free to put this in `lib/Traits/TraitsClasses/CogCatalogItemTraits.ts` if you want to keep everything in one file

2024-06-25 07:48 UTC, nf-s commented on package.json
> +    "geotiff": "^2.1.3",
Can this be removed? As it isn't directly used in TerriaJS

2024-06-25 07:48 UTC, nf-s commented on lib/Models/Catalog/CatalogItems/CogCatalogItem.ts
> +  tileDiscardPolicy = undefined as any;
Because `TIFFImageryProvider` doesn't extend cesium's `ImageryProvider` I don't think these options are doing anything.

So I think we should remove them, but also change the magnification/minification filter to nearest to get rid of that weird blur. It also reduces artifacts between tiles

```suggestion
  _defaultMagnificationFilter = TextureMagnificationFilter.NEAREST;
  _defaultMinificationFilter = TextureMinificationFilter.NEAREST;
```

2024-06-25 09:32 UTC, staffordsmith83 commented
> Awesome stuff, thanks @staffordsmith83 !
> 
> I haven't finished my review yet - but thought I should post what I have
> 
> Did we end up deciding how to handle projections that aren't cesium native (wgs84 and webmercator)?
> 
> If are going to allow reprojection, I think we should add a "short report" so there's a message in the workbench. As it looks like there are some reprojection issues
> 
> <img alt="image" width="1279" src="https://private-user-images.githubusercontent.com/6187649/342588543-1fc9c5c7-b680-4844-a484-e5ea009c7b5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDc1NjMsIm5iZiI6MTcxOTMwNzI2MywicGF0aCI6Ii82MTg3NjQ5LzM0MjU4ODU0My0xZmM5YzVjNy1iNjgwLTQ4NDQtYTQ4NC1lNWVhMDA5YzdiNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMDkyMTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGIwYjU0MzE4ZDVmMWQ2NjVmODY2ZjI3NzkyMmY0ZjYyOGJlNzhiOWZkZDU1MmRkNDAxM2U1ZDljMzFhNmY2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JjRdDGfPDLJHltWpqCIMFXNF4zhJARB21G-Y7navGas">
> * [Reprojection example - epsg:32756](http://ci.terria.io/cog-support-cesium-only-1/#clean&https://gist.githubusercontent.com/staffordsmith83/9a6ba12479100a810dadcf0119242913/raw/d1c0fdf888e8477be8f044721b7cd1e2ec33c907/cogs_three_groups.json&start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22%2F%2FSupported+Datasets%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2F%2FSupported+Datasets%2FCOG+Test+Whian+Whian%22%3A%7B%22opacity%22%3A1%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%2FSupported+Datasets%22%5D%2C%22type%22%3A%22cog%22%7D%2C%22%2F%22%3A%7B%22type%22%3A%22group%22%7D%7D%2C%22workbench%22%3A%5B%22%2F%2FSupported+Datasets%2FCOG+Test+Whian+Whian%22%5D%2C%22timeline%22%3A%5B%5D%2C%22initialCamera%22%3A%7B%22west%22%3A153.41161478960097%2C%22south%22%3A-28.061298397857612%2C%22east%22%3A153.42650335865278%2C%22north%22%3A-28.042438926989824%2C%22position%22%3A%7B%22x%22%3A-5039055.0838929955%2C%22y%22%3A2521274.6258177627%2C%22z%22%3A-2982430.527881199%7D%2C%22direction%22%3A%7B%22x%22%3A0.7892395196302652%2C%22y%22%3A-0.3948933959656323%2C%22z%22%3A0.47027671266661586%7D%2C%22up%22%3A%7B%22x%22%3A-0.4205699368373914%2C%22y%22%3A0.21043078364419832%2C%22z%22%3A0.8825190159557363%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22viewerMode%22%3A%223dSmooth%22%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.4999%2C%22settings%22%3A%7B%22baseMaximumScreenSpaceError%22%3A2%2C%22useNativeResolution%22%3Atrue%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-positron%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse%7D%2C%22stories%22%3A%5B%5D%7D%5D%7D)
> * [uluru reprojection example](http://ci.terria.io/cog-support-cesium-only-1/#clean&https://gist.githubusercontent.com/staffordsmith83/9a6ba12479100a810dadcf0119242913/raw/d1c0fdf888e8477be8f044721b7cd1e2ec33c907/cogs_three_groups.json&start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22%2F%2FSupported+Datasets%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2F%2FSupported+Datasets%2FCOG+Test+Whian+Whian%22%3A%7B%22opacity%22%3A1%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%2FSupported+Datasets%22%5D%2C%22type%22%3A%22cog%22%7D%2C%22%2F%2FSupported+Datasets%2FUSGS+Elevation%22%3A%7B%22opacity%22%3A1%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%2FSupported+Datasets%22%5D%2C%22type%22%3A%22cog%22%7D%2C%22%2F%2FSupported+Datasets%2FCOG+Test+Uluru%281%29%22%3A%7B%22knownContainerUniqueIds%22%3A%5B%22%2F%2FSupported+Datasets%22%5D%2C%22type%22%3A%22cog%22%7D%2C%22%2F%22%3A%7B%22type%22%3A%22group%22%7D%7D%2C%22workbench%22%3A%5B%22%2F%2FSupported+Datasets%2FCOG+Test+Uluru%281%29%22%5D%2C%22timeline%22%3A%5B%5D%2C%22initialCamera%22%3A%7B%22west%22%3A130.5873113853551%2C%22south%22%3A-25.81071236732281%2C%22east%22%3A130.59992099929624%2C%22north%22%3A-25.794414151922386%2C%22position%22%3A%7B%22x%22%3A-3739698.691339093%2C%22y%22%3A4364165.316830322%2C%22z%22%3A-2760066.4969194573%7D%2C%22direction%22%3A%7B%22x%22%3A0.585815228580093%2C%22y%22%3A-0.683636494180984%2C%22z%22%3A0.43527194004160996%7D%2C%22up%22%3A%7B%22x%22%3A-0.2832269316883932%2C%22y%22%3A0.33052105372270196%2C%22z%22%3A0.9002990271084452%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22viewerMode%22%3A%223dSmooth%22%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.5%2C%22settings%22%3A%7B%22baseMaximumScreenSpaceError%22%3A2%2C%22useNativeResolution%22%3Atrue%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-positron%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse%7D%2C%22stories%22%3A%5B%5D%7D%5D%7D)
> 
> I actually think we should disable reprojection until we fully understand how it works - and can validate that it is accurate enough for visualisation purposes - I think it is doing some weird stuff on the edges of tiles - especially when using nearest pixel interpolation.
> 
> There are also some tiling and pixel interpolation issues with the 4326 COG
> 
> * [open aerial map example](http://ci.terria.io/cog-support-cesium-only-1/#clean&https://gist.githubusercontent.com/staffordsmith83/9a6ba12479100a810dadcf0119242913/raw/d1c0fdf888e8477be8f044721b7cd1e2ec33c907/cogs_three_groups.json&start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22%2F%2FSupported+Datasets%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2F%2FSupported+Datasets%2FDrone+image+from+Open+Aerial+Map%22%3A%7B%22knownContainerUniqueIds%22%3A%5B%22%2F%2FSupported+Datasets%22%5D%2C%22type%22%3A%22cog%22%7D%2C%22%2F%22%3A%7B%22type%22%3A%22group%22%7D%7D%2C%22workbench%22%3A%5B%22%2F%2FSupported+Datasets%2FDrone+image+from+Open+Aerial+Map%22%5D%2C%22timeline%22%3A%5B%5D%2C%22initialCamera%22%3A%7B%22west%22%3A-90.8706279985145%2C%22south%22%3A14.589539101881737%2C%22east%22%3A-90.8702281108131%2C%22north%22%3A14.590095198398252%2C%22position%22%3A%7B%22x%22%3A-93788.20540361805%2C%22y%22%3A-6173117.815926865%2C%22z%22%3A1596232.9717276145%7D%2C%22direction%22%3A%7B%22x%22%3A0.014701393256942266%2C%22y%22%3A0.9676422770093419%2C%22z%22%3A-0.2518973854181122%7D%2C%22up%22%3A%7B%22x%22%3A0.0038266364342477723%2C%22y%22%3A0.25186831804353843%2C%22z%22%3A0.9677539497307769%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22viewerMode%22%3A%223dSmooth%22%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.4999%2C%22settings%22%3A%7B%22baseMaximumScreenSpaceError%22%3A2%2C%22useNativeResolution%22%3Atrue%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-positron%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse%7D%2C%22stories%22%3A%5B%5D%7D%5D%7D)
> 
> This example gets much better when the `TextureMagnificationFilter` is set to `Nearest` instead of the default `Linear` value - I think we should change the default to `Nearest` (see comment below)
> 
> ## On texture filters + pixel interpolation
> ### Reprojection example
> <img alt="Screenshot 2024-06-25 at 5 02 57 PM" width="2000" src="https://private-user-images.githubusercontent.com/6187649/342618010-ad5b68a8-391b-49a7-b649-4eb2412924da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6Imt [...]

2024-06-25 09:35 UTC, staffordsmith83 commented on lib/Models/Terria.ts
> +  proj4ServiceBaseUrl: string;
OK will do. That was from an earlier change Im sure it can go back to optional no problem

2024-06-25 09:36 UTC, staffordsmith83 commented on lib/Traits/TraitsClasses/CogRenderOptionsTraits.ts
> +}
OK can do that. Its going to grow if I have time for second traits PR though

2024-06-25 09:36 UTC, staffordsmith83 commented on package.json
> +    "geotiff": "^2.1.3",
yes, was from previous code when using TIFFImageryProvider in third part folder sorry

2024-06-25 09:37 UTC, staffordsmith83 commented on lib/Models/Catalog/CatalogItems/CogCatalogItem.ts
> +  tileDiscardPolicy = undefined as any;
Great find! Yes, once again these were to fix something in one of my earlier iterations, hopefully no longer needed.

2024-06-26 01:46 UTC, staffordsmith83 commented on lib/Models/Terria.ts
> +  proj4ServiceBaseUrl: string;
done

2024-06-26 01:46 UTC, staffordsmith83 commented on lib/Traits/TraitsClasses/CogRenderOptionsTraits.ts
> +}
done

2024-06-26 01:46 UTC, staffordsmith83 commented on lib/Models/Catalog/CatalogItems/CogCatalogItem.ts
> +  tileDiscardPolicy = undefined as any;
done

2024-06-26 01:46 UTC, staffordsmith83 commented on package.json
> +    "geotiff": "^2.1.3",
done

2024-06-26 01:47 UTC, staffordsmith83 commented
Just going to implement short report now. We can disable all reprojection later if decided.

2024-06-26 05:26 UTC, nf-s requested changes
The "nearest pixel + nearest filter" 4326 example is much better than "nearest pixel + linear filter" - but it is still doing weird things with the pixel sizes. The no data values are also quite different from the actual data.

<img width="1211" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/6a8b9d55-6d93-4997-bea0-a2694c5b1f8d">

Any COG in 4326 or 3857 _should_ be able to be visualised without these kinds of artefacts in cesium. What also concerns me is that when you change `resampleMethod` to `linear` you get these really narrow pixels, which should be square(ish). I think there are bugs in how `TIFFImageryProvider` calculates the number of pixels (and how they are arranged) in each tile/overview.

I don't mind if the data isn't perfectly represented at lower zoom levels/lower LOD - but as you zoom in it should get more accurate, and then at some point you should be able to see actual pixel values. This may not be that important for imagery data, but I think it is more important for scientific gridded data. For example, if we were to bring in climate projection data, which is quite coarse spatially, I'm worried that the visualisation may be misrepresenting the data.

I think there may be some fundamental issues with `TIFFImageryProvider` here. I was aware of possible issues with how it approaches reprojection - but I wasn't aware that it has issues with CRSs that are native to cesium. 

I apologise if this seems overly critical. 

As we add more "raw" data formats to Terria - especially a new class of format (as this is the first raster format) - I think it is very important that we can be certain that data is not being misrepresented. At this stage I don't think we should merge this in until we have identified the issues in `TIFFImageryProvider`. In my opinion, I think the minimum requirements for Geotiff/COG support in Terria is support for 4326 and 3857, and when you zoom in you should be able to see the actual pixel values with reasonable accuracy.

@na9da and @steve9164 what do you think?

2024-06-26 07:14 UTC, staffordsmith83 commented
I can find some netCDF CMIP6 data or similar climate data to add and see how that looks too.
No worries I think its important to preserve the quality of the Terria product, if you guys dont think the way TIFFImageryProvider works is rigorous enough then I dont mind. I agree misrepresentation of data is a dangerous thing.

2024-06-27 01:35 UTC, staffordsmith83 commented
@nf-s Ill add some gridded climate data examples from here: https://registry.opendata.aws/nex-gddp-cmip6/

2024-06-27 02:33 UTC, staffordsmith83 commented
The dataset should look like this: 
![image](https://github.com/TerriaJS/terriajs/assets/7980991/391f3120-9977-4ad3-982a-93352f3ef127)

2024-06-27 23:59 UTC, staffordsmith83 commented
Here is a separate draft PR to implement a shortReport warning about non-native projection COGs: https://github.com/TerriaJS/terriajs/pull/7226

It is incomplete, but the strategy to finish it is in the description of the PR.

2024-06-28 00:00 UTC, staffordsmith83 commented
Regarding resampling error: Hongfaqiu is aware of the issue and is going to try to fix it next week. With a bit of luck after that a merge from upstream and COGs will be good to go! https://github.com/hongfaqiu/TIFFImageryProvider/issues/30#issuecomment-2193947286

2024-08-27 00:02 UTC, imakihi commented
@staffordsmith83
Thank you for working on this! I checked if the value picking issue I described in https://github.com/TerriaJS/terriajs/pull/6833 was solved. It looks like the value picking on the 3D mode working correctly!!! Great!!

2024-08-27 00:04 UTC, staffordsmith83 commented
Dear @imakihi thats great! Im no longer working on the Terria team, so Im not sure when they plan to merge this, @nf-s whats the plans with COGs? I could try to find some time over the summer to help get it done?

2024-08-27 19:10 UTC, imakihi commented
Hi @staffordsmith83 
I didn't know that you left the Terria team. Thank you for starting this great feature and worked on it.
I think this COG capability benefits many Terria users.
Thank you!

2024-08-27 21:24 UTC, staffordsmith83 commented
> Hi @staffordsmith83 I didn't know that you left the Terria team. Thank you for starting this great feature and worked on it. I think this COG capability benefits many Terria users. Thank you!

My pleasure Hiroo! Hope to meet you some day at a conference or something :-)

2024-08-29 05:51 UTC, nf-s commented
> Dear @imakihi thats great! Im no longer working on the Terria team, so Im not sure when they plan to merge this, @nf-s whats the plans with COGs? I could try to find some time over the summer to help get it done?

We are in a bit of a frenzy at the moment, and I'm about to be off for 2 weeks, but it would be awesome to get this merged in soon. Thanks for offering your time @staffordsmith83! That is very kind of you. I'll see if someone in the team has time to take a look first to save you the effort - I'll let you know if I can find someone to look at it over the next 2 weeks 🙂

2024-08-30 02:21 UTC, imakihi commented
@nf-s Thank so much you. It would be super super cool if Terria users could use COG data.

2024-08-30 03:39 UTC, staffordsmith83 commented
Thanks @nf-s yes let me know, Im crazy flat out but I would just love to see this get finished, lets make it happen together!

2024-09-04 23:35 UTC, na9da commented
@staffordsmith83 - Thanks for offering. I'll get some time next week to have a look. I'll need to get familiar with COG stuff though. Will ping here if I have any questions :)

2024-09-05 00:10 UTC, staffordsmith83 commented
@na9da OK Ill keep an eye on this ticket!

2024-09-18 00:15 UTC, imakihi commented
@na9da @nf-s 
I was wondering if you had time to think about this COG support...

2024-09-18 00:30 UTC, na9da commented
@imakihi - sorry i haven't had a chance to look at it yet. But hopefully soon.

2024-10-16 02:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TerriaJS/terriajs?pullRequest=7209) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/TerriaJS/terriajs?pullRequest=7209) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: na9da<br/>:x: staffordsmith83<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TerriaJS/terriajs?pullRequest=7209) it.</sub>

2024-10-16 07:57 UTC, na9da commented
Hey @staffordsmith83 @nf-s - I have updated the PR with the following main changes:

- [Upgraded](https://github.com/TerriaJS/TIFFImageryProvider/pull/1) terriajs-tiff-imagery-provider to match latest upstream `main`
  - `linear` mode has been replaced with a better `bilinear` mode which looks great, so I have made it the default.
     Here's a comparison of nearest (left) & bilinear (right) modes ([CI test link](http://ci.terria.io/cog-support-cesium-only-1/#share=s-t5i1wQbevr0dGRXNqUgTfjMNHcl))
  - minimized custom changes so that merges from upstream becomes easier (turned of prettier etc)
  - changes [documented here](https://github.com/TerriaJS/TIFFImageryProvider/blob/5927f06e6463423897c6e9a58ec387fb241f72e7/packages/TIFFImageryProvider/CHANGES-FOR-TERRIA.md)
- CogCatalogItem changes
  - switched imagery provider loading to use the `fromUrl` API (the `url` option is deprecated in upstream).
 
Pending: update test cases

2024-10-17 01:05 UTC, na9da commented
@nf-s new test url - http://ci.terria.io/cog-support-cesium-only-1/#share=s-t5i1wQbevr0dGRXNqUgTfjMNHcl&clean&https://gist.githubusercontent.com/na9da/18ce40ab4d93a722932c3efe5c947139/raw/b06ed050745f57ba9b081e7700e6504ea6719a9b/cogs.json

2024-10-17 01:44 UTC, nf-s requested changes
Hi @na9da 

Looks great @na9da ! I checked the 4326 and 3857 examples and compared with QGIS, and the output looks good! 

I think the default resampling method should be "nearest" to most closely represent the data - while it might make sense to apply linear/billinear transformation to imagery by default - a lot, if not most, raster data is not imagery, it is scientific data, where the pixel bounds are quite important. There are also weird artifacts along tile borders with linear/billinear resampling.

Is it possible to up the "quality" of the COGs? It looks like the imagery provider is always a step behind, so you can always see pixels - even with the quality slider set to "max quality".

For example - here I can clearly see the pixels, but the TIFF is has quite a few more level-of-details to load

- http://ci.terria.io/cog-support-cesium-only-1/#share=s-mY9ifiWSeLGF9ZCQVunRv0iIH7v&clean&https://gist.githubusercontent.com/na9da/18ce40ab4d93a722932c3efe5c947139/raw/b06ed050745f57ba9b081e7700e6504ea6719a9b/cogs.json

<img width="773" alt="image" src="https://github.com/user-attachments/assets/c25e1c6f-3e4e-4108-9013-617ee78cb474">

One other small comment, when I paste in a TIFF into "Add Web Data" without specifying "Cloud Optimized GeoTIFF", there is a error - it would be good to have support for `.tif`, `.tiff`, `.geotiff`

Thanks!

2024-10-17 03:55 UTC, nf-s commented
Also did a quick test to see if alignment is correct - and it looks to be!good!

<img width="2560" alt="image" src="https://github.com/user-attachments/assets/60b8c06c-2881-4ed2-8b54-967eb0019a25">

2024-10-18 05:17 UTC, na9da commented
On the quality, i had a look - the particular opendrone dataset has 8 images in the TIFF pyramid. The imagery provider seems to be correctly picking and cycling through them as Cesium requests new zoom levels.

Not sure exactly whats causing the pixelized look. In 3D mode, there might be different active zoom levels (see screenshot below), which could be one reason.
![image](https://github.com/user-attachments/assets/acc0d39d-00d4-4d0c-8ab1-10133c5d3801)

However, I switched the map to 2d mode, which resulted in a single zoom level for all tiles, but the pixelization didn't improve much.

The other thought is, the COG has 8 images, but does that map linearly with zoom levels, i.e at zoom=5, is it correct to use the 5th image in the COG, or is there some other math to figure out which zoom level to use.

Also, not sure if there is any other stretching happening from adjusting for image shape (aspect ratio related).

The other possibility, is some processing happening in cesium that makes the images look less sharp. I tried changing the cesium imagery layer to use "NEAREST" sampling ([as suggested here](https://community.cesium.com/t/blurry-imagery-faa-vfr-tiles/31540/3)), which makes it slightly less blurry

![image](https://github.com/user-attachments/assets/49015e4e-85b5-4296-ae51-80f30a79f752)
(left with NEAREST filter slightly sharper vs right with default linear)

I also compared it with openlayers, which looks super crisp. No idea how to get anywhere close to that.

![image](https://github.com/user-attachments/assets/8c8f31fa-2b5a-411e-84cc-e4b4e4c0d487)
(openlayers - no pixelation at all)

TLDR; not much clue where that pixelation is coming from.

2024-10-18 07:20 UTC, staffordsmith83 commented
Great to see the upstream changes have improved this! Ill try to find some some for a closer look next week. Thanks @na9da !

2024-10-20 13:15 UTC, nf-s commented
All 

> On the quality, i had a look - the particular opendrone dataset has 8 images in the TIFF pyramid. The imagery provider seems to be correctly picking and cycling through them as Cesium requests new zoom levels.
> 
> Not sure exactly whats causing the pixelized look. In 3D mode, there might be different active zoom levels (see screenshot below), which could be one reason. ![image](https://private-user-images.githubusercontent.com/1430/377710720-acc0d39d-00d4-4d0c-8ab1-10133c5d3801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAxNjcsIm5iZiI6MTcyOTQyOTg2NywicGF0aCI6Ii8xNDMwLzM3NzcxMDcyMC1hY2MwZDM5ZC0wMGQ0LTRkMGMtOGFiMS0xMDEzM2M1ZDM4MDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTMxMTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTFhMDM4ODhkYzJhMDJhMDQyZTlmYmIyOTcxZmFlMmMzMzgwNjE0NDZlNmQ0NzUzN2QxZGEyZWMxMzI4OGVkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jYQJnZ8_Xr-h98Hw9-RanYbIIQ4xYlLuM1oUxOX2-Lg)
> 
> However, I switched the map to 2d mode, which resulted in a single zoom level for all tiles, but the pixelization didn't improve much.
> 
> The other thought is, the COG has 8 images, but does that map linearly with zoom levels, i.e at zoom=5, is it correct to use the 5th image in the COG, or is there some other math to figure out which zoom level to use.
> 
> Also, not sure if there is any other stretching happening from adjusting for image shape (aspect ratio related).
> 
> The other possibility, is some processing happening in cesium that makes the images look less sharp. I tried changing the cesium imagery layer to use "NEAREST" sampling ([as suggested here](https://community.cesium.com/t/blurry-imagery-faa-vfr-tiles/31540/3)), which makes it slightly less blurry Edit: I see you already explored this in a previous comment
> 
> ![image](https://private-user-images.githubusercontent.com/1430/377729872-49015e4e-85b5-4296-ae51-80f30a79f752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAxNjcsIm5iZiI6MTcyOTQyOTg2NywicGF0aCI6Ii8xNDMwLzM3NzcyOTg3Mi00OTAxNWU0ZS04NWI1LTQyOTYtYWU1MS04MGYzMGE3OWY3NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTMxMTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIyMjMwNjI5M2IyNjM1MDNhZDdkZDY3NjJhMGM1NmZlZmEzZjhlZjU5ZTgzOTdmYzliZWE4YjJhMDU5NjIyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZQV2ul-_XV95biB3N493VoSKlYHZqDzF9aNHs5aw2Ac) (left with NEAREST filter slightly sharper vs right with default linear)
> 
> I also compared it with openlayers, which looks super crisp. No idea how to get anywhere close to that.
> 
> ![image](https://private-user-images.githubusercontent.com/1430/377730442-8c8f31fa-2b5a-411e-84cc-e4b4e4c0d487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAxNjcsIm5iZiI6MTcyOTQyOTg2NywicGF0aCI6Ii8xNDMwLzM3NzczMDQ0Mi04YzhmMzFmYS0yYjVhLTQxMWUtODRjYy1lNGI0ZTRjMGQ0ODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTMxMTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc0NDZjMmU3MzRiZjkzYzI2YmQxNGJmODQ3YmU0MTI4MzZiMDdhMzA0NjE1NzBmOWRlOGE2MWJlMzM3NjgzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-ZJ69oN9qK8YqeKd92p6QlzmpE9prdvvZZI--GFcJCw) (openlayers - no pixelation at all)
> 
> TLDR; not much clue where that pixelation is coming from.

All good, thanks for checking @na9da !
The quality issue is just a nice-to-have for me. We can improve it later. It could be something in TIFFImageryProvider causing the issue.

Thanks a lot @staffordsmith83 and @na9da !
We're so close to merging this in 😄 !

2024-10-20 23:44 UTC, na9da commented
@nf-s thanks for the review.

I have now fixed some additional CI errors (related to a change @types/leaflet).

Also made [this change](https://github.com/TerriaJS/terriajs/pull/7209/commits/afa94ef3b277c536bb6e14111dc138a06786777c) to free the imageryProvider when not used. The imageryProvider creates a bunch of webworkers. This change ensures that they get freed when the item is removed from the workbench. Ideally, we would have a `destroy()` life-cycle method for catalog items that would make this more explicit instead of using `onBecomeUnobserved`. Maybe we should add it when we deal with https://github.com/TerriaJS/terriajs/issues/4816

2024-10-22 03:18 UTC, nf-s approved these changes
LGTM thanks a lot @staffordsmith83 and @na9da !

2024-10-22 03:30 UTC, merged

2024-10-25 03:30 UTC, staffordsmith83 commented
Awesome, its in! Thanks @na9da and @nf-s

2024-10-26 00:11 UTC, imakihi commented
Super cool. @na9da @nf-s @staffordsmith83