Fix overflow
TerriaJS/terriajs pull request #7290
Opened 2024-10-18 03:00 UTC by ykiu

### What this PR does

This PR ensures the item search tool and the story builder render appropriately when their contents are long.

#### Before

<img width="1481" alt="image" src="https://github.com/user-attachments/assets/ba51e744-63fb-4828-9e51-5ff943ac8a2f">

**The item search tool**: when the search parameter list is long the search tool grows out of the viewport.
**The story builder**: when there are many stories, the capture scene button at the bottom is pushed out of the viewport.

#### After

<img width="1483" alt="image" src="https://github.com/user-attachments/assets/fc46c4c1-57de-43eb-8e12-a7600e05d860">

**The item search tool**: the search parameter list is now scrollable.
**The story builder**: the capture scene button stays inside the viewport.

### Test me

Start locally, then open the following link:

[http://localhost:3001/#start=%7B%22initSources...%7D%5D%7D](http://localhost:3001#start=%7B%22initSources%22%3A%5B%7B%22workbench%22%3A%5B%22Buildings%22%2C%22Terrain%22%5D%2C%22catalog%22%3A%5B%7B%22id%22%3A%22Terrain%22%2C%22type%22%3A%22cesium-terrain%22%2C%22ionAccessToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3NGI5ZDM0Mi1jZDIzLTRmMzEtOTkwYi0zZTk4Yzk3ODZlNzQiLCJpZCI6NDA2NDYsImlhdCI6MTYwODk4MzAwOH0.3rco62ErML11TMSEflsMqeUTCDbIH6o4n4l5sssuedE%22%2C%22ionAssetId%22%3A696407%7D%2C%7B%22id%22%3A%22Buildings%22%2C%22type%22%3A%223d-tiles%22%2C%22url%22%3A%22https%3A%2F%2Fassets.cms.plateau.reearth.io%2Fassets%2F18%2F14c28e-9962-44f4-a6bf-950e0b2f7724%2F22209_shimada-shi_city_2023_citygml_1_op_bldg_3dtiles_lod1%2Ftileset.json%22%2C%22search%22%3A%7B%22providerType%22%3A%22indexed%22%2C%22providerOptions%22%3A%7B%22indexRootUrl%22%3A%22https%3A%2F%2Ftest-kiuchi-pss.s3.amazonaws.com%2F20241017_sample_index%2F22209_shimada-shi_city_2023_citygml_1_op_bldg_3dtiles_lod1%2FindexRoot.json%22%7D%2C%22resultTemplate%22%3A%22%3Cspan+style%3D%27font-weight%3A+bold%3B%27%3E%7B%7Bgml%3Aname%7D%7D%3C%2Fspan%3E+%7B%7Bgml_id%7D%7D%22%2C%22parameters%22%3A%5B%7B%22id%22%3A%22gml%3Aname%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22uro%3ABuildingIDAttribute_uro%3Aprefecture%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22uro%3ABuildingIDAttribute_uro%3Acity%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22uro%3ABuildingDataQualityAttribute_uro%3Alod1HeightType%22%2C%22name%22%3A%22AnExtremelyLongParameterNameWithoutWhiteSpacesToEnsureItWrapsAppropriately%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22uro%3ARealEstateIDAttribute_uro%3ArealEstateIDOfBuilding%22%2C%22name%22%3A%22An+extremely+long+parameter+name+to+ensure+it+wraps+appropriately%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E6%B9%AF%E6%97%A5%E5%B7%9D%E6%B0%B4%E7%B3%BB%E6%B9%AF%E6%97%A5%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L1%EF%BC%88%E8%A8%88%E7%94%BB%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E6%B9%AF%E6%97%A5%E5%B7%9D%E6%B0%B4%E7%B3%BB%E6%B9%AF%E6%97%A5%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L2%EF%BC%88%E6%83%B3%E5%AE%9A%E6%9C%80%E5%A4%A7%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E6%A0%83%E5%B1%B1%E5%B7%9D%E6%B0%B4%E7%B3%BB%E6%A0%83%E5%B1%B1%E5%B7%9D%E3%83%BB%E6%9C%A8%E5%B1%8B%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L1%EF%BC%88%E8%A8%88%E7%94%BB%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E6%A0%83%E5%B1%B1%E5%B7%9D%E6%B0%B4%E7%B3%BB%E6%A0%83%E5%B1%B1%E5%B7%9D%E3%83%BB%E6%9C%A8%E5%B1%8B%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L2%EF%BC%88%E6%83%B3%E5%AE%9A%E6%9C%80%E5%A4%A7%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E4%BA%95%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L1%EF%BC%88%E8%A8%88%E7%94%BB%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E4%BA%95%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L2%EF%BC%88%E6%83%B3%E5%AE%9A%E6%9C%80%E5%A4%A7%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E6%B4%A5%E8%B0%B7%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L1%EF%BC%88%E8%A8%88%E7%94%BB%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E6%B4%A5%E8%B0%B7%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L2%EF%BC%88%E6%83%B3%E5%AE%9A%E6%9C%80%E5%A4%A7%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E4%BB%A3%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L1%EF%BC%88%E8%A8%88%E7%94%BB%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E4%BB%A3%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L2%EF%BC%88%E6%83%B3%E5%AE%9A%E6%9C%80%E5%A4%A7%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%9C%9F%E7%A0%82%E7%81%BD%E5%AE%B3%E3%83%AA%E3%82%B9%E3%82%AF_%E5%9C%B0%E3%81%99%E3%81%B9%E3%82%8A_%E5%8C%BA%E5%9F%9F%E5%8C%BA%E5%88%86%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%9C%9F%E7%A0%82%E7%81%BD%E5%AE%B3%E3%83%AA%E3%82%B9%E3%82%AF_%E6%80%A5%E5%82%BE%E6%96%9C%E5%9C%B0%E3%81%AE%E5%B4%A9%E8%90%BD_%E5%8C%BA%E5%9F%9F%E5%8C%BA%E5%88%86%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%9C%9F%E7%A0%82%E7%81%BD%E5%AE%B3%E3%83%AA%E3%82%B9%E3%82%AF_%E5%9C%9F%E7%9F%B3%E6%B5%81_%E5%8C%BA%E5%9F%9F%E5%8C%BA%E5%88%86%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%5D%7D%7D%5D%2C%22stories%22%3A%5B%7B%22title%22%3A%22Story+%231%22%2C%22text%22%3A%22This+is+the+description+of+story+%231%22%2C%22id%22%3A%2290046c02-1e00-4610-8493-cccfab9cb9ee%22%2C%22shareData%22%3A%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%5D%7D%7D%2C%7B%22title%22%3A%22Story+%232%22%2C%22text%22%3A%22This+is+the+description+of+story+%232%22%2C%22id%22%3A%2290046c02-1e00-4610-8493-cccfab9cb9ee%22%2C%22shareData%22%3A%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%5D%7D%7D%2C%7B%22title%22%3A%22Story+%233%22%2C%22text%22%3A%22This+is+the+description+of+story+%233%22%2C%22id%22%3A%2290046c02-1e00-4610-8493-cccfab9cb9ee%22%2C%22shareData%22%3A%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%5D%7D%7D%2C%7B%22title%22%3A%22Story+%234%22%2C%22text%22%3A%22This+is+the+description+of+story+%234%22%2C%22id%22%3A%2290046c02-1e00-4610-8493-cccfab9cb9ee%22%2C%22shareData%22%3A%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%5D%7D%7D%2C%7B%22title%22%3A%22Story+%235%22%2C%22text%22%3A%22This+is+the+description+of+story+%235%22%2C [...]

2024-10-18 03:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TerriaJS/terriajs?pullRequest=7290) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TerriaJS/terriajs?pullRequest=7290) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TerriaJS/terriajs?pullRequest=7290) it.</sub>

2024-10-22 02:36 UTC, na9da requested changes
@ykiu - thanks again for the improvements.

I have left a small comment.

2024-10-22 02:36 UTC, na9da commented on lib/ReactViews/Story/story-editor.scss
I guess we could remove the entire `.editor` class?

2024-10-23 08:46 UTC, ykiu commented on lib/ReactViews/Story/story-editor.scss
Thanks for your suggestion. I think some other classes could be removed, too. I'm working on it.

2024-10-23 09:04 UTC, ykiu commented
@na9da  Thank you for reviewing. I removed unused CSS classes.

I noticed the position of the story menu was off in my initial version, so I fixed it as well. The menu grows upwards/downwards depending on the space available, as it previously did:

<img width="310" alt="image" src="https://github.com/user-attachments/assets/5e39c93b-7c0e-4864-aff4-f94f1dc93570">

<img width="292" alt="image" src="https://github.com/user-attachments/assets/460c84b0-b582-4404-9545-5b5e6068869c">

Please verify it's not brokwn by using the following link:

[http://localhost:3001/#start=%7B%22initSources...%7D%5D%7D](http://localhost:3001#start=%7B%22initSources%22%3A%5B%7B%22workbench%22%3A%5B%22Buildings%22%2C%22Terrain%22%5D%2C%22catalog%22%3A%5B%7B%22id%22%3A%22Terrain%22%2C%22type%22%3A%22cesium-terrain%22%2C%22ionAccessToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3NGI5ZDM0Mi1jZDIzLTRmMzEtOTkwYi0zZTk4Yzk3ODZlNzQiLCJpZCI6NDA2NDYsImlhdCI6MTYwODk4MzAwOH0.3rco62ErML11TMSEflsMqeUTCDbIH6o4n4l5sssuedE%22%2C%22ionAssetId%22%3A696407%7D%2C%7B%22id%22%3A%22Buildings%22%2C%22type%22%3A%223d-tiles%22%2C%22url%22%3A%22https%3A%2F%2Fassets.cms.plateau.reearth.io%2Fassets%2F18%2F14c28e-9962-44f4-a6bf-950e0b2f7724%2F22209_shimada-shi_city_2023_citygml_1_op_bldg_3dtiles_lod1%2Ftileset.json%22%2C%22search%22%3A%7B%22providerType%22%3A%22indexed%22%2C%22providerOptions%22%3A%7B%22indexRootUrl%22%3A%22https%3A%2F%2Ftest-kiuchi-pss.s3.amazonaws.com%2F20241017_sample_index%2F22209_shimada-shi_city_2023_citygml_1_op_bldg_3dtiles_lod1%2FindexRoot.json%22%7D%2C%22resultTemplate%22%3A%22%3Cspan+style%3D%27font-weight%3A+bold%3B%27%3E%7B%7Bgml%3Aname%7D%7D%3C%2Fspan%3E+%7B%7Bgml_id%7D%7D%22%2C%22parameters%22%3A%5B%7B%22id%22%3A%22gml%3Aname%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22uro%3ABuildingIDAttribute_uro%3Aprefecture%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22uro%3ABuildingIDAttribute_uro%3Acity%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22uro%3ABuildingDataQualityAttribute_uro%3Alod1HeightType%22%2C%22name%22%3A%22AnExtremelyLongParameterNameWithoutWhiteSpacesToEnsureItWrapsAppropriately%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22uro%3ARealEstateIDAttribute_uro%3ArealEstateIDOfBuilding%22%2C%22name%22%3A%22An+extremely+long+parameter+name+to+ensure+it+wraps+appropriately%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E6%B9%AF%E6%97%A5%E5%B7%9D%E6%B0%B4%E7%B3%BB%E6%B9%AF%E6%97%A5%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L1%EF%BC%88%E8%A8%88%E7%94%BB%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E6%B9%AF%E6%97%A5%E5%B7%9D%E6%B0%B4%E7%B3%BB%E6%B9%AF%E6%97%A5%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L2%EF%BC%88%E6%83%B3%E5%AE%9A%E6%9C%80%E5%A4%A7%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E6%A0%83%E5%B1%B1%E5%B7%9D%E6%B0%B4%E7%B3%BB%E6%A0%83%E5%B1%B1%E5%B7%9D%E3%83%BB%E6%9C%A8%E5%B1%8B%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L1%EF%BC%88%E8%A8%88%E7%94%BB%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E6%A0%83%E5%B1%B1%E5%B7%9D%E6%B0%B4%E7%B3%BB%E6%A0%83%E5%B1%B1%E5%B7%9D%E3%83%BB%E6%9C%A8%E5%B1%8B%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L2%EF%BC%88%E6%83%B3%E5%AE%9A%E6%9C%80%E5%A4%A7%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E4%BA%95%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L1%EF%BC%88%E8%A8%88%E7%94%BB%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E4%BA%95%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L2%EF%BC%88%E6%83%B3%E5%AE%9A%E6%9C%80%E5%A4%A7%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E6%B4%A5%E8%B0%B7%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L1%EF%BC%88%E8%A8%88%E7%94%BB%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E6%B4%A5%E8%B0%B7%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L2%EF%BC%88%E6%83%B3%E5%AE%9A%E6%9C%80%E5%A4%A7%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E4%BB%A3%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L1%EF%BC%88%E8%A8%88%E7%94%BB%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%A4%A7%E4%BA%95%E5%B7%9D%E6%B0%B4%E7%B3%BB%E5%A4%A7%E4%BB%A3%E5%B7%9D%EF%BC%88%E9%83%BD%E9%81%93%E5%BA%9C%E7%9C%8C%E7%AE%A1%E7%90%86%E5%8C%BA%E9%96%93%EF%BC%89_L2%EF%BC%88%E6%83%B3%E5%AE%9A%E6%9C%80%E5%A4%A7%E8%A6%8F%E6%A8%A1%EF%BC%89_%E6%B5%B8%E6%B0%B4%E3%83%A9%E3%83%B3%E3%82%AF%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%9C%9F%E7%A0%82%E7%81%BD%E5%AE%B3%E3%83%AA%E3%82%B9%E3%82%AF_%E5%9C%B0%E3%81%99%E3%81%B9%E3%82%8A_%E5%8C%BA%E5%9F%9F%E5%8C%BA%E5%88%86%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%9C%9F%E7%A0%82%E7%81%BD%E5%AE%B3%E3%83%AA%E3%82%B9%E3%82%AF_%E6%80%A5%E5%82%BE%E6%96%9C%E5%9C%B0%E3%81%AE%E5%B4%A9%E8%90%BD_%E5%8C%BA%E5%9F%9F%E5%8C%BA%E5%88%86%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%2C%7B%22id%22%3A%22%E5%9C%9F%E7%A0%82%E7%81%BD%E5%AE%B3%E3%83%AA%E3%82%B9%E3%82%AF_%E5%9C%9F%E7%9F%B3%E6%B5%81_%E5%8C%BA%E5%9F%9F%E5%8C%BA%E5%88%86%22%2C%22queryOptions%22%3A%7B%22fuzzy%22%3A2%7D%7D%5D%7D%7D%5D%2C%22stories%22%3A%5B%7B%22title%22%3A%22Story+%231%22%2C%22text%22%3A%22This+is+the+description+of+story+%231%22%2C%22id%22%3A%227d3ccec6-4b92-4b83-830f-a2ee4793d581%22%2C%22shareData%22%3A%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%5D%7D%7D%2C%7B%22title%22%3A%22Story+%232%22%2C%22text%22%3A%22This+is+the+description+of+story+%232%22%2C%22id%22%3A%22bc11cf2a-cf90-4112-807b-8a8c1c8b0efd%22%2C%22shareData%22%3A%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%5D%7D%7D%2C%7B%22title%22%3A%22Story+%233%22%2C%22text%22%3A%22This+is+the+description+of+story+%233%22%2C%22id%22%3A%220ae925f6-b98c-411c-b855-78a92ec38981%22%2C%22shareData%22%3A%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%5D%7D%7D%2C%7B%22title%22%3A%22Story+%234%22%2C%22text%22%3A%22This+is+the+description+of+story+%234%22%2C%22id%22%3A%22e5153f9d-98ad-4c31-b02e-127acadbbd61%22%2C%22shareData%22%3A%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%5D%7D%7D%2C%7B%22title%22%3A%22Story+%235%22%2C%22text%22%3A%22This+is+the+description+of+story+%235%22%2C%22id%22%3A%2207f7f863-5b27-4e5d-9d82-2f141c191bd3%22%2C%22shareData%22%3A%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%5D%7D%7D%2C%7B%22title%22%3A%22Story+%236%22%2C%22text%22%3A%22This+is+the+description+of+story+%236%22%2C%22id%22%3A%2261eac71f-07de-4c48-8796-db436309f1a5%2 [...]

2024-10-25 03:44 UTC, na9da approved these changes
Good catch @ykiu - i missed it.

Good to go!

2024-10-25 03:58 UTC, merged