Tile ArcGis FeatureServer requests
TerriaJS/terriajs pull request #7370
Opened 2024-12-13 07:12 UTC by nf-s

### Tile ArcGis FeatureServer requests

Fixes https://github.com/TerriaJS/terriajs/issues/3661

This is a description of what I've done in this PR, especially explaining choices made to make the reviewer's job easier. If I don't replace this paragraph with an actual description, my PR will probably be ignored.

### Test me

How should reviewers test this? (Hint: If you want to provide a test catalog item, [create a Gist](https://gist.github.com/) of its catalog JSON, add its url and your branch name to this url: `http://ci.terria.io/<branch name>/#clean&<raw url of your gist>` , and then paste that in the body of this PR)

### Checklist

- [ ] There are unit tests to verify my changes are correct or unit tests aren't applicable (if so, write quick reason why unit tests don't exist)
- [ ] I've updated relevant documentation in `doc/`.
- [ ] I've updated CHANGES.md with what I changed.
- [ ] I've provided instructions in the PR description on how to test this PR.

2024-12-14 17:24 UTC, zoran995 commented
It might be of interest to look into #6840 the mentioned layer is failing with

> {
    "code": 400,
    "message": "",
    "details": [
        "'Invalid field: objectid' parameter is invalid"
    ]
}

2024-12-24 01:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TerriaJS/terriajs?pullRequest=7370) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/TerriaJS/terriajs?pullRequest=7370) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: tephenavies<br/>:white_check_mark: ljowen<br/>:white_check_mark: pjonsson<br/>:white_check_mark: na9da<br/>:white_check_mark: nf-s<br/>:x: Lawrence Owen<br/><hr/>**Lawrence Owen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TerriaJS/terriajs?pullRequest=7370) it.</sub>

2025-02-04 05:48 UTC, nf-s commented
There is a bug I haven't been able to fix. It occurs in the 3D (cesium) viewer, with layers that have a minimum zoom level.

- [Test link](http://ci.terria.io/tile-arcgis-featureserver/#start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22__User-Added_Data__%22%3A%7B%22isOpen%22%3Atrue%2C%22members%22%3A%5B%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%22%5D%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%22%3A%7B%22isOpen%22%3Atrue%2C%22url%22%3A%22https%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%22%2C%22knownContainerUniqueIds%22%3A%5B%22__User-Added_Data__%22%5D%2C%22type%22%3A%22esri-group%22%7D%2C%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%2FNSW_Administrative_Boundaries_Theme_multiCRS%2FFeatureServer%22%3A%7B%22isOpen%22%3Afalse%2C%22knownContainerUniqueIds%22%3A%5B%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%22%5D%2C%22type%22%3A%22esri-featureServer-group%22%7D%2C%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%2FNSW_Water_Theme_multiCRS%2FFeatureServer%22%3A%7B%22isOpen%22%3Atrue%2C%22knownContainerUniqueIds%22%3A%5B%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%22%5D%2C%22type%22%3A%22esri-featureServer-group%22%7D%2C%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%2FNSW_Water_Theme_multiCRS%2FFeatureServer%2F6%22%3A%7B%22knownContainerUniqueIds%22%3A%5B%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%2FNSW_Water_Theme_multiCRS%2FFeatureServer%22%5D%2C%22type%22%3A%22esri-featureServer%22%7D%2C%22%2F%22%3A%7B%22type%22%3A%22group%22%7D%7D%2C%22workbench%22%3A%5B%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%2FNSW_Water_Theme_multiCRS%2FFeatureServer%2F6%22%5D%2C%22timeline%22%3A%5B%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%2FNSW_Water_Theme_multiCRS%2FFeatureServer%2F6%22%5D%2C%22initialCamera%22%3A%7B%22west%22%3A150.76903928591705%2C%22south%22%3A-33.87578706692171%2C%22east%22%3A150.8090195823401%2C%22north%22%3A-33.82816771331238%2C%22position%22%3A%7B%22x%22%3A-4631421.501641395%2C%22y%22%3A2589577.8893886614%2C%22z%22%3A-3535371.165973835%7D%2C%22direction%22%3A%7B%22x%22%3A0.7248641500756964%2C%22y%22%3A-0.40529504282460255%2C%22z%22%3A0.5570528630182615%7D%2C%22up%22%3A%7B%22x%22%3A-0.4862116981624778%2C%22y%22%3A0.27185672102561875%2C%22z%22%3A0.8304770362888781%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22viewerMode%22%3A%223dSmooth%22%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.4999%2C%22settings%22%3A%7B%22baseMaximumScreenSpaceError%22%3A2%2C%22useNativeResolution%22%3Atrue%2C%22alwaysShowTimeline%22%3Afalse%2C%22baseMapId%22%3A%22basemap-natural-earth-II%22%2C%22terrainSplitDirection%22%3A0%2C%22depthTestAgainstTerrainEnabled%22%3Afalse%7D%2C%22pickedFeatures%22%3A%7B%22providerCoords%22%3A%7B%22%2Fhttps%3A%2F%2Fportal.spatial.nsw.gov.au%2Fserver%2Frest%2Fservices%2FNSW_Water_Theme_multiCRS%2FFeatureServer%2F6%22%3A%7B%22x%22%3A30107%2C%22y%22%3A19661%2C%22level%22%3A15%7D%2C%22https%3A%2F%2Fstorage.googleapis.com%2Fterria-datasets-public%2Fbasemaps%2Fnatural-earth-tiles%2F%7Bz%7D%2F%7Bx%7D%2F%7BreverseY%7D.png%22%3A%7B%22x%22%3A117%2C%22y%22%3A76%2C%22level%22%3A7%7D%7D%2C%22pickCoords%22%3A%7B%22lat%22%3A-33.84944461506681%2C%22lng%22%3A150.77458130421803%2C%22height%22%3A-0.00913791767729486%7D%2C%22current%22%3A%7B%22name%22%3A5373%2C%22hash%22%3A52653753116%7D%2C%22entities%22%3A%5B%5D%7D%2C%22stories%22%3A%5B%5D%7D%5D%7D)

2025-02-05 08:34 UTC, nf-s commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> -
No longer needed due to `softMinimumZoom`

2025-02-05 08:37 UTC, nf-s commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> -      });
This has been moved into `lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts`

2025-02-05 08:52 UTC, nf-s commented on lib/ModelMixins/FeatureInfoUrlTemplateMixin.ts
> +
This fixes the "read outside reactive context" warnings we were getting with `featureInfoUrlTemplate`

2025-02-05 09:15 UTC, nf-s commented on lib/Table/TableColorMap.ts
> +      colorTraits.mapType === "bin"
Loosen condition here, as we need to allow Discrete/Continuous color maps when colorColumn is undefined (eg empty)

2025-02-05 09:15 UTC, nf-s commented on lib/Table/TableColorMap.ts
> +      colorTraits.mapType === "enum"
Same as above...

2025-02-05 09:18 UTC, nf-s commented on lib/Table/TableLegendStratum.ts
Instead of returning no legend, we now hide the legend - this is so we can override it in `ArcGisFeatureServerCatalogItem`

2025-02-05 21:01 UTC, pjonsson commented on lib/ModelMixins/FeatureInfoUrlTemplateMixin.ts
> +        this.featureInfoUrlTemplate ?? "",
The statement on the line before this statement defines `featureInofUrlTemplate`. Since that is already defined, is there a reason to not use that here?

2025-02-05 21:05 UTC, pjonsson commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> +    request?: Request | undefined
What is the convention for ?-variables in TerriaMap, do the type need to include `| undefined`, or is the absence of the variable enough?

2025-02-05 21:06 UTC, pjonsson commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> +      throw TerriaError.from(`Level: ${level} is below softMinimumLevel`);
Can the value of `this.softMinimumLevel` be seen when this error is triggered, or should that be included in the error message?

2025-02-05 21:08 UTC, pjonsson commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> +    if (!tile) throw TerriaError.from("Failed to get tile");
Is there a tile name that could be included, or is it obvious what tile that failed when this happens?

2025-02-05 21:10 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsArcGisPbfSource.ts
> +    // eslint-disable-next-line @typescript-eslint/no-unused-vars
Can this suppression be avoided by naming the parameter `_request?`?

2025-02-05 21:19 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +    case "MultiLineString":
Are the cases sorted in some way? If not, it should be possible to group them so there's fewer return statements:
```TypeScript
case "Point":
case "MultiPoint":
  return GeomType.Point;
...
case "MultiLineString":
case "MultiPolygon":
  return GeomType.Line;
```

2025-02-05 21:24 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +          g1 = [g1[0] * scale, g1[1] * scale];
Is the LHS `g1` conceptually a pair `(x, y)`?  I think it would be easier to read separate  `x` and `y` variables instead of `g1[0]` and `g1[1]`

2025-02-06 01:36 UTC, nf-s commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> +    if (!tile) throw TerriaError.from("Failed to get tile");
It tile is `undefined` then there are bigger problems - there is no appropriate source, or the `view` hasn't been setup. I have modified the message to reflect this

2025-02-06 12:01 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +    case "MultiPoint":
Does the input for this function ever come from the code updated in #7432, or is that a separate code path?

2025-02-06 12:03 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +            const x = g2[0];
Is this function body identical to the function body in the else-branch on line 271?

2025-02-06 12:03 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +            const y = g2[1];
Is `x` and `y` meant to not be scaled?

2025-02-06 12:04 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +            g2 = [x * scale, y * scale];
I think this `g2` is no longer used.

2025-02-06 12:07 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +        const geom = f.geometry as any as [number, number][][];
There is a (disabled) ESLint rule in the recommended rules that complains about use of `any`, does `as unknown as [number, number][][]` work here?

2025-02-06 12:10 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +      let numVertices = 0;
I don't think these two need to be initialized (looks like they are assigned in all code paths below).

2025-02-07 00:34 UTC, nf-s commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +            const y = g2[1];
Good pickup, my brain wasn't working yesterday!

2025-02-07 00:48 UTC, nf-s commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +            const y = g2[1];
Fixed

2025-02-07 00:49 UTC, nf-s commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +            const x = g2[0];
Yes, but I think it is fine. IMO generally not worth refactoring duplication out unless there are more then 2 instances

2025-02-07 00:49 UTC, nf-s commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +      let numVertices = 0;
Strictly speaking no, but they make sense as default values, so i'm going to leave them there

2025-02-07 00:50 UTC, nf-s commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +    case "MultiPoint":
Most likely yes, but depends on a few other factors

2025-02-07 00:51 UTC, nf-s commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +    case "MultiPoint":
Just merged your PR in

2025-02-07 06:45 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +    case "MultiPoint":
I'm not sure if your yes means that the input comes from the other code or if it is a separate code path, but thank you for merging the PR.

2025-02-07 06:52 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +      }[f.type];
I think commit e32e129e7bb addresses the same issue without resorting to comparing to the raw values in the enum.

2025-02-14 02:46 UTC, na9da requested changes
@nf-s - this is an awesome feature improvement. Great work on the implementation. 

I have left some comments in the code review plus a couple of other observations:

- I noticed in some cases, the column values differ between protomap and geojson rendering modes. Example protomap vs geojson. This affects the symbology. Not sure if it is easily fixable though.
protomap:
![image](https://github.com/user-attachments/assets/debeca4f-17c3-42a0-89da-3cbd62982f3c)
geojson:
![image](https://github.com/user-attachments/assets/f170c247-585c-42e4-a49c-aa2964d8047b)

- Not something from this PR but I think the [second parameter here](https://github.com/TerriaJS/terriajs/blob/aabc08069787f606b223aad09a6983fa74b53544/lib/Models/Catalog/Esri/ArcGisFeatureServerCatalogItem.ts#L189-L190) should be `this._featureServer`. This for example affects the behaviour when splitting an item for compare.

2025-02-14 02:46 UTC, na9da commented on lib/Models/Catalog/Esri/ArcGisFeatureServerCatalogItem.ts
> +          `WARNING: Terria does not support visual variables in ArcGisFeatureService SimpleRenderers`
Small typo: should this say `UniqueValueRenderers` instead of `SimpleRenderers`? Same for classbreaks

2025-02-14 02:46 UTC, na9da commented on lib/Models/Catalog/Esri/ArcGisFeatureServerCatalogItem.ts
Suggestion: is it worth splitting styling and associated functions into a separate Stratum and file?

2025-02-14 02:46 UTC, na9da commented on lib/Models/Catalog/Esri/ArcGisFeatureServerCatalogItem.ts
> +  fields?: Field[];
Like for the other types, is there a spec link for `FeatureServer` we can point to in comment?

2025-02-14 02:46 UTC, na9da commented on lib/Map/Vector/Protomaps/ProtomapsArcGisPbfSource.ts
> +        // request: request
Would it work if we clone the `request`? AFAICT, for imagery layers, it only sets some [flags](https://github.com/CesiumGS/cesium/blob/82e59ed00973bd3866d9d175914f7e38dee927dd/packages/engine/Source/Scene/ImageryLayer.js#L1164-L1168) at this stage in the code path. Cancellation might work even without passing `request` as it seems to create a[ new Request by default](https://github.com/CesiumGS/cesium/blob/82e59ed00973bd3866d9d175914f7e38dee927dd/packages/engine/Source/Core/Resource.js#L121).

2025-02-14 02:46 UTC, na9da commented on lib/Map/ColorMap/ColorMap.ts
> +  abstract mapValueToColor(value: JsonValue | undefined): Readonly<Color>;
Doubt: is this change required? Most implementations of `ColorMap` assumes the param to be `string | ...`. Also the `JsonValue` [imported here](https://github.com/TerriaJS/terriajs/blob/a73f22e2f6c5cb2fd1da023c2dc3654c9d7f9a0e/lib/Map/Vector/Protomaps/tableStyleToProtomaps.ts#L6) comes from `protomap-leaflet`

2025-02-14 02:46 UTC, na9da commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> +  async requestImage(x: number, y: number, level: number, request: Request) {
The `request` param should be optional right?

2025-02-14 02:46 UTC, na9da commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> +    if (this.softMinimumLevel && level < this.softMinimumLevel)
Nitpick: Maybe not an issue here, but is it better to test `this.softMinimumLevel !== undefined` as it makes the intent a bit more clear.

2025-02-14 02:46 UTC, na9da commented on lib/ModelMixins/FeatureInfoUrlTemplateMixin.ts
> +                currentTime,
Doubt: Should we do `currentTime ?? JulianDate.now()` instead so that it is always current and not the time when the closure was generated.

2025-02-14 02:46 UTC, na9da commented on lib/ModelMixins/GeojsonMixin.ts
> +export function isMultiLineString(json: any): json is Feature<MultiLineString> {
At some point maybe we should probably extract these functions to a new file. I have found them useful in other contexts.

2025-02-14 02:46 UTC, na9da commented on lib/Table/TableColorMap.ts
> +      colorTraits.mapType === "bin"
Nitpick: is there a scope to make the intent more clear for the condition? One possibility might be to assign first to a temporarily variable like: `const isScalarColorColumn = colorColumn?.type === TableColumnType.scalar`.

2025-02-14 02:46 UTC, na9da commented on lib/Models/Workflows/TableStylingWorkflow.ts
> +        d.imageryProvider instanceof ProtomapsImageryProvider
Nitpick: There's also [ImageryParts.is()](https://github.com/TerriaJS/terriajs/blob/aabc08069787f606b223aad09a6983fa74b53544/lib/ModelMixins/MappableMixin.ts#L72) for this test

2025-02-14 02:46 UTC, na9da commented on lib/Map/Vector/Protomaps/ProtomapsGeojsonSource.ts
> +      }[f.type];
In my testing that wasn't working. I think it is a subtle TS gotcha. `FeatureTypes` is an (ambient) `enum` defined in `.d.ts` file. No JS code is generated for it and so `geojsonvt.FeatureTypes`  will be `undefined` at run time. 

Had it been defined in a `.ts` file, it should have worked.

2025-02-14 04:25 UTC, na9da commented
On the cesium error, I think it is happening when the `imageryProvider` gets destroyed while it is being loaded. This happens when the [trait change inside requestImage](https://github.com/TerriaJS/terriajs/blob/a73f22e2f6c5cb2fd1da023c2dc3654c9d7f9a0e/lib/ModelMixins/MinMaxLevelMixin.ts#L75-L85) triggers a chain of events that results in our Cesium.ts removing it from the `scene`.

One fix we could do at our end is to wrap these [setTrait calls](https://github.com/TerriaJS/terriajs/blob/a73f22e2f6c5cb2fd1da023c2dc3654c9d7f9a0e/lib/ModelMixins/MinMaxLevelMixin.ts#L75-L85) within `runLater` - which gives cesium a chance to finish processing before the imagery provider gets destroyed.

2025-02-26 00:20 UTC, nf-s commented on lib/Table/TableColorMap.ts
> +      colorTraits.mapType === "bin"
I agree it is confusing, I'm not sure adding variables like `isScalarColorColumn` will add clarity, as there will still need to be an explicit check that `colorColumn` is defined too. 

I added a comment above with:

```
TODO: Move all of these default values/behaviours to TableAutomaticStylesStratum - ideally no use of colorColumn is needed here
```

I think `TableColorMap` (amongst other `TableStyle`/`TableColumn` things) go against the pattern of using strata to drive default values. Ideally, `colorTraits.mapType` is set to an appropriate value in `TableAutomaticStylesStratum.styles`, but I thought that would be too far-reaching for this PR.

I just added another comment for later

```
TableAutomaticStylesStratum should also set default values for colorTraits.mapType, colors, etc
```

2025-02-26 07:19 UTC, nf-s commented on lib/Models/Catalog/Esri/ArcGisFeatureServerCatalogItem.ts
Yep good idea! Done

2025-02-26 07:29 UTC, nf-s commented on lib/Map/Vector/Protomaps/ProtomapsArcGisPbfSource.ts
> +        // request: request
I tried this and got some weird behaviour - with requests being dropped. I'm not sure how cesium internals handle this, but I think it doesn't like multiple requests for a single tile.

2025-02-26 07:32 UTC, nf-s commented on lib/Map/ColorMap/ColorMap.ts
> +  abstract mapValueToColor(value: JsonValue | undefined): Readonly<Color>;
I just opened the type up slightly, to make it easier to use in 

https://github.com/TerriaJS/terriajs/blob/b7e5b425c0296ba249c41079725c93d6ad7d2b98/lib/Map/Vector/Protomaps/tableStyleToProtomaps.ts#L140

2025-02-26 08:11 UTC, nf-s commented
> I noticed in some cases, the column values differ between protomap and geojson rendering modes. This affects the symbology. Not sure if it is easily fixable though.

This was due to how `TableColumn` was guessing the type from the values - it was the type to `scalar` which was stripping the comments. `FeatureServerStratum` now sets column types using the `esriFieldType`. This won't solve the general case (for all tabular, geojson data), but at least it fixes it here. I don't particularly want to tweak the `TableColumn` type guessing at this stage.

> On the cesium error, I think it is happening when the imageryProvider gets destroyed while it is being loaded. This happens when the [trait change inside requestImage](https://github.com/TerriaJS/terriajs/blob/a73f22e2f6c5cb2fd1da023c2dc3654c9d7f9a0e/lib/ModelMixins/MinMaxLevelMixin.ts#L75-L85) triggers a chain of events that results in our Cesium.ts removing it from the scene.
> 
> One fix we could do at our end is to wrap these [setTrait calls](https://github.com/TerriaJS/terriajs/blob/a73f22e2f6c5cb2fd1da023c2dc3654c9d7f9a0e/lib/ModelMixins/MinMaxLevelMixin.ts#L75-L85) within runLater - which gives cesium a chance to finish what it is doing before the imagery provider gets destroyed.

I tried adding `runLater`, it did fix the crashing, but the selected features being unselected after the share link loads. I'm also hesitant to add that change without further testing at this stage.

2025-02-26 13:44 UTC, pjonsson commented on lib/Core/GeoJson.ts
> +    isJsonObject(json.geometry, false) &&
These 3 lines are repeated in almost every function, is there a name for what they are checking so that check could be factored out to its own function?

2025-02-26 13:55 UTC, pjonsson commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> +    const origin = new Point(
Can this definition be moved to before the `tile` definition on line 265 and used to define its origin as well?

2025-02-26 13:57 UTC, pjonsson commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> +      minX: PROTOMAPS_DEFAULT_TILE_SIZE * coords.x - PROTOMAPS_TILE_BUFFER,
Is the RHS here `origin.x - PROTOMAPS_TILE_BUFFER`?

2025-02-26 14:02 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsArcGisPbfSource.ts
> +    points = feature.geometry.coordinates;
Can this be a single branch with the condition `isMultilineString(feature) || isPolygon(feature)`?

2025-02-26 14:06 UTC, pjonsson commented on lib/Map/Vector/Protomaps/ProtomapsArcGisPbfSource.ts
> +      const transformedG2 = [
This code block seems familiar, are the components `x` and `y` this time as well?

2025-02-26 14:12 UTC, pjonsson commented on lib/Map/Vector/Protomaps/tableStyleToProtomaps.ts
> +    return () => {
Why does TypeScript not flag this as a type error, isn't the return type a function that takes a number?

2025-02-26 14:21 UTC, pjonsson commented on lib/Models/Catalog/Esri/esriStyleToTableStyle.ts
> +export function convertEsriPointSizeToPixels(pointSize?: number) {
Does this type signature permit forgetting the parameter, so the caller:
```typescript
const x = convertEsriPointSizeToPixels();
```
will pass the compiler without errors? Is that what you want?

2025-02-26 14:22 UTC, pjonsson commented on lib/Models/Catalog/Esri/esriStyleToTableStyle.ts
> +  esriColor?: null | number[] | undefined
Same comment here about potentially forgetting the parameter without compiler errors.

2025-02-26 14:29 UTC, pjonsson commented on lib/Table/TableStyleMap.ts
> +        for (
I think a one line comment explaining what the loop computes would be nice.

Not sure if the continue in the body adds anything.

2025-02-27 01:50 UTC, nf-s commented
At this stage, I’d like to keep this PR focused and avoid too many rounds of review. A lot of the changes here are just moving functions between files for better organization, and I generally try to keep those kinds of refactors minimal to reduce the risk of breaking things.

While your suggestions are valuable, I think we need to balance time and effort on TerriaJS. Right now, new features (like this one) and bug fixes are the bigger priorities over broader code improvements. Let’s keep this PR moving, and we can revisit larger refactors when the timing makes sense 🙂

2025-02-27 22:31 UTC, pjonsson commented
> While your suggestions are valuable, I think we need to balance time and effort on TerriaJS. Right now, new features (like this one) and bug fixes are the bigger priorities over broader code improvements.

TerriaJS is your code base, so you decide the priorities. I do feel that a PR with a diffstat of +4513-1363 viewed in the Github "Files changed" tab makes it difficult for us to know what parts of the code that have been changed and which parts that have just been moved.

The onToggle fix in this PR seemed to be missing the other place I introduced that bug, so I split out the complete onToggle fix to #7511 and referenced the commit where the problem was introduced.

2025-03-03 03:49 UTC, na9da commented on lib/Map/Vector/Protomaps/tableStyleToProtomaps.ts
> +    return () => {
It is valid JS/TS to omit arguments.

2025-03-03 03:51 UTC, na9da commented on lib/Models/Catalog/Esri/esriStyleToTableStyle.ts
> +export function convertEsriPointSizeToPixels(pointSize?: number) {
this should be fine, `convertEsriPointSizeToPixels` can be called as `convertEsriPointSizeToPixels(10)` or `convertEsriPointSizeToPixels(undefined)` or `convertEsriPointSizeToPixels()`.

2025-03-03 03:52 UTC, na9da commented on lib/Map/ImageryProvider/ProtomapsImageryProvider.ts
> +      minX: PROTOMAPS_DEFAULT_TILE_SIZE * coords.x - PROTOMAPS_TILE_BUFFER,
not sure why you think so.

2025-03-03 04:00 UTC, na9da commented on lib/Map/Vector/Protomaps/ProtomapsArcGisPbfSource.ts
> +    points = feature.geometry.coordinates;
That to me is a pretty trivial difference. I would leave such decisions to the author unless it makes a huge performance or readability improvement.

2025-03-03 05:08 UTC, na9da approved these changes
Approving.

> I tried adding runLater, it did fix the crashing, but the selected features being unselected after the share link loads. I'm also hesitant to add that change without further testing at this stage.

For future reference:
`mapItems` is recomputed not because `scaleWorkbenchInfo` changed - there is no direct dependence of mapItems on `scaleWorkbenchInfo`. It is actually a side-effect of inserting a new `"defaults"` stratum which re-computes `strataTopToBottom` and then everything that depends on it (including `mapItems`). When that happens `Cesium.ts` destroys the layer - in the midst of a request, causing some inconsistency in Cesium's internal state.

One other fix might be to pre-emptly add the `"defaults"` stratum  in the [Mixin constructor](https://github.com/TerriaJS/terriajs/blob/ddb88d05b58ba6f80e0120a81b7e9e0a51f0c1c4/lib/ModelMixins/MinMaxLevelMixin.ts#L19). This seems to fix the disappearing feature info panel: 
```
  this.setTrait(CommonStrata.defaults, "scaleWorkbenchInfo", undefined);
```

2025-03-04 05:31 UTC, merged